package bench

import (
	"context"
	"fmt"
	"io"
	"os"
	"time"

	"github.com/WuKongIM/WuKongIM/cmd/wkcli/internal/command"
	"github.com/spf13/cobra"
)

var executeSend = executeSendConfig

// NewCommand builds the bench subcommand.
func NewCommand(deps command.Deps) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bench",
		Short: "Run WuKongIM benchmark helpers",
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := cmd.Help(); err != nil {
				return command.Exit{Code: command.ExitInternal, Message: err.Error()}
			}
			return command.Exit{Code: command.ExitConfig}
		},
	}
	cmd.AddCommand(newSendCommand(deps))
	return cmd
}

func newSendCommand(deps command.Deps) *cobra.Command {
	cfg := sendConfig{
		Clients:       1,
		Messages:      100000,
		Size:          "128B",
		Channel:       defaultChannel,
		Channels:      1,
		ChannelPrefix: defaultChannelPrefix,
		ChannelType:   "group",
		ChannelPick:   channelPickRoundRobin,
		BatchSize:     1,
		AckTimeout:    5 * time.Second,
		UIDPrefix:     defaultUIDPrefix,
		DevicePrefix:  defaultDevicePrefix,
	}
	cmd := &cobra.Command{
		Use:   "send",
		Short: "Benchmark WKProto SEND throughput and SENDACK latency",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if deps.ContextDir != nil {
				cfg.ContextDir = *deps.ContextDir
			}
			if !cfg.NoProgress && !cfg.JSON && isTerminalWriter(deps.Stdout) {
				cfg.ProgressWriter = deps.Stdout
			}
			result, err := executeSend(cmd.Context(), cfg)
			if err != nil {
				return command.Exit{Code: command.ExitConfig, Message: err.Error()}
			}
			if err := writeSendResult(deps, cfg, result); err != nil {
				return command.Exit{Code: command.ExitInternal, Message: err.Error()}
			}
			if result.Result != resultPass {
				return command.Exit{Code: 3}
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&cfg.ContextName, "context", "", "Named wkcli context to use")
	cmd.Flags().StringArrayVar(&cfg.ServerAddrs, "server", nil, "WuKongIM HTTP API server address; repeat or use comma-separated values")
	cmd.Flags().StringArrayVar(&cfg.GatewayAddrs, "gateway", nil, "WKProto TCP gateway address; repeat or use comma-separated values")
	cmd.Flags().StringVar(&cfg.BenchToken, "bench-token", "", "Optional bearer token for bench/v1 discovery APIs")
	cmd.Flags().IntVar(&cfg.Clients, "clients", cfg.Clients, "Number of concurrent WKProto clients")
	cmd.Flags().IntVar(&cfg.Messages, "msgs", cfg.Messages, "Total number of messages to send")
	cmd.Flags().StringVar(&cfg.Size, "size", cfg.Size, "Payload size such as 128B, 1KB, or 1MiB")
	cmd.Flags().StringVar(&cfg.Payload, "payload", "", "Literal payload to send instead of generated bytes")
	cmd.Flags().IntVar(&cfg.BatchSize, "batch", cfg.BatchSize, "Messages per SendBatch call")
	cmd.Flags().IntVar(&cfg.Throughput, "throughput", 0, "Aggregate target messages per second; 0 disables throttling")
	cmd.Flags().DurationVar(&cfg.Sleep, "sleep", 0, "Delay between batches for each client")
	cmd.Flags().DurationVar(&cfg.AckTimeout, "ack-timeout", cfg.AckTimeout, "SENDACK wait timeout")
	cmd.Flags().IntVar(&cfg.ConnectRate, "connect-rate", 0, "Maximum client connects per second; 0 disables throttling")
	cmd.Flags().StringVar(&cfg.Channel, "channel", cfg.Channel, "Single channel ID used when --channels=1")
	cmd.Flags().IntVar(&cfg.Channels, "channels", cfg.Channels, "Number of generated channels")
	cmd.Flags().StringVar(&cfg.ChannelPrefix, "channel-prefix", cfg.ChannelPrefix, "Prefix for generated channels when --channels>1")
	cmd.Flags().StringVar(&cfg.ChannelType, "channel-type", cfg.ChannelType, "Channel type: person, group, or cmd")
	cmd.Flags().StringVar(&cfg.ChannelPick, "channel-pick", cfg.ChannelPick, "Channel selection policy: round_robin or random")
	cmd.Flags().Int64Var(&cfg.RandomSeed, "seed", 1, "Random seed used by --channel-pick=random")
	cmd.Flags().StringVar(&cfg.UIDPrefix, "uid-prefix", cfg.UIDPrefix, "Prefix for generated client UIDs")
	cmd.Flags().StringVar(&cfg.DevicePrefix, "device-prefix", cfg.DevicePrefix, "Prefix for generated device IDs")
	cmd.Flags().StringVar(&cfg.Token, "token", "", "Shared WKProto CONNECT token")
	cmd.Flags().BoolVar(&cfg.NoProgress, "no-progress", false, "Disable progress output")
	cmd.Flags().BoolVar(&cfg.JSON, "json", false, "Print final summary as JSON")
	cmd.Flags().StringVar(&cfg.CSVPath, "csv", "", "Write final summary CSV to this path")
	return cmd
}

func isTerminalWriter(w io.Writer) bool {
	file, ok := w.(*os.File)
	if !ok {
		return false
	}
	info, err := file.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}

func executeSendConfig(ctx context.Context, cfg sendConfig) (sendResult, error) {
	normalized, err := normalizeSendConfig(cfg)
	if err != nil {
		return sendResult{}, err
	}
	return runSend(ctx, normalized)
}

func writeSendResult(deps command.Deps, cfg sendConfig, result sendResult) error {
	if cfg.CSVPath != "" {
		out, err := formatCSVSummary(result)
		if err != nil {
			return err
		}
		if err := os.WriteFile(cfg.CSVPath, []byte(out), 0o600); err != nil {
			return err
		}
	}
	if cfg.JSON {
		out, err := formatJSONSummary(result)
		if err != nil {
			return err
		}
		_, err = fmt.Fprint(deps.Stdout, out)
		return err
	}
	_, err := fmt.Fprint(deps.Stdout, formatHumanSummary(result))
	return err
}
