// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: pkg/wkhook/webhook.proto

package wkhook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventStatus int32

const (
	EventStatus_Error   EventStatus = 0
	EventStatus_Success EventStatus = 1
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "Error",
		1: "Success",
	}
	EventStatus_value = map[string]int32{
		"Error":   0,
		"Success": 1,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_wkhook_webhook_proto_enumTypes[0].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_pkg_wkhook_webhook_proto_enumTypes[0]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_wkhook_webhook_proto_rawDescGZIP(), []int{0}
}

type EventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EventReq) Reset() {
	*x = EventReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_wkhook_webhook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReq) ProtoMessage() {}

func (x *EventReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wkhook_webhook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReq.ProtoReflect.Descriptor instead.
func (*EventReq) Descriptor() ([]byte, []int) {
	return file_pkg_wkhook_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *EventReq) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *EventReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status EventStatus `protobuf:"varint,1,opt,name=status,proto3,enum=wkhook.EventStatus" json:"status,omitempty"`
	Data   []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EventResp) Reset() {
	*x = EventResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_wkhook_webhook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResp) ProtoMessage() {}

func (x *EventResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wkhook_webhook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResp.ProtoReflect.Descriptor instead.
func (*EventResp) Descriptor() ([]byte, []int) {
	return file_pkg_wkhook_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *EventResp) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_Error
}

func (x *EventResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_wkhook_webhook_proto protoreflect.FileDescriptor

var file_pkg_wkhook_webhook_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x6b, 0x68, 0x6f, 0x6f, 0x6b, 0x2f, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x6b, 0x68, 0x6f,
	0x6f, 0x6b, 0x22, 0x34, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x77, 0x6b, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x25, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x32, 0x44, 0x0a,
	0x0e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x32, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x12, 0x10,
	0x2e, 0x77, 0x6b, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x77, 0x6b, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x77, 0x6b, 0x68, 0x6f, 0x6f, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_wkhook_webhook_proto_rawDescOnce sync.Once
	file_pkg_wkhook_webhook_proto_rawDescData = file_pkg_wkhook_webhook_proto_rawDesc
)

func file_pkg_wkhook_webhook_proto_rawDescGZIP() []byte {
	file_pkg_wkhook_webhook_proto_rawDescOnce.Do(func() {
		file_pkg_wkhook_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_wkhook_webhook_proto_rawDescData)
	})
	return file_pkg_wkhook_webhook_proto_rawDescData
}

var file_pkg_wkhook_webhook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_wkhook_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_wkhook_webhook_proto_goTypes = []interface{}{
	(EventStatus)(0),  // 0: wkhook.EventStatus
	(*EventReq)(nil),  // 1: wkhook.EventReq
	(*EventResp)(nil), // 2: wkhook.EventResp
}
var file_pkg_wkhook_webhook_proto_depIdxs = []int32{
	0, // 0: wkhook.EventResp.status:type_name -> wkhook.EventStatus
	1, // 1: wkhook.WebhookService.SendWebhook:input_type -> wkhook.EventReq
	2, // 2: wkhook.WebhookService.SendWebhook:output_type -> wkhook.EventResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_wkhook_webhook_proto_init() }
func file_pkg_wkhook_webhook_proto_init() {
	if File_pkg_wkhook_webhook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_wkhook_webhook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_wkhook_webhook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_wkhook_webhook_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_wkhook_webhook_proto_goTypes,
		DependencyIndexes: file_pkg_wkhook_webhook_proto_depIdxs,
		EnumInfos:         file_pkg_wkhook_webhook_proto_enumTypes,
		MessageInfos:      file_pkg_wkhook_webhook_proto_msgTypes,
	}.Build()
	File_pkg_wkhook_webhook_proto = out.File
	file_pkg_wkhook_webhook_proto_rawDesc = nil
	file_pkg_wkhook_webhook_proto_goTypes = nil
	file_pkg_wkhook_webhook_proto_depIdxs = nil
}
