package model

import "time"

// Target describes the black-box WuKongIM deployment endpoints used by wkbench.
type Target struct {
	// APIAddrs are HTTP API base addresses for normal client/server requests.
	APIAddrs []string `json:"api_addrs" yaml:"api_addrs"`
	// GatewayTCPAddrs are client gateway TCP addresses used by load workers.
	GatewayTCPAddrs []string `json:"gateway_tcp_addrs" yaml:"gateway_tcp_addrs"`
	// Metrics contains optional metrics scrape settings for reports and doctor checks.
	Metrics MetricsConfig `json:"metrics" yaml:"metrics"`
	// BenchAPI controls access to the benchmark-only server API surface.
	BenchAPI BenchAPIConfig `json:"bench_api" yaml:"bench_api"`
}

// BenchAPIConfig configures the benchmark preparation HTTP API exposed by the target.
type BenchAPIConfig struct {
	// Enabled must be true because wkbench is a black-box client of the bench API.
	Enabled bool `json:"enabled" yaml:"enabled"`
	// Addrs are optional explicit bench API base addresses; APIAddrs are used when empty.
	Addrs []string `json:"addrs" yaml:"addrs"`
	// Token is an optional shared token for protected benchmark preparation endpoints.
	Token string `json:"token" yaml:"token"`
}

// MetricsConfig describes optional target metrics endpoints.
type MetricsConfig struct {
	// Enabled indicates whether wkbench should collect target metrics.
	Enabled bool `json:"enabled" yaml:"enabled"`
	// Addrs are metrics endpoint base addresses.
	Addrs []string `json:"addrs" yaml:"addrs"`
}

// Worker describes one wkbench worker process available to a run coordinator.
type Worker struct {
	// ID is the stable worker identifier used in run assignments.
	ID string `json:"id" yaml:"id"`
	// Addr is the worker control address.
	Addr string `json:"addr" yaml:"addr"`
	// Weight is the relative share of load assigned to this worker.
	Weight float64 `json:"weight" yaml:"weight"`
	// ControlToken is an optional shared token for worker control requests.
	ControlToken string `json:"control_token" yaml:"control_token"`
	// Tags are free-form labels for worker selection.
	Tags map[string]string `json:"tags" yaml:"tags"`
}

// WorkerSet groups configured workers for a benchmark run.
type WorkerSet struct {
	// Workers is the list of available wkbench worker processes.
	Workers []Worker `json:"workers" yaml:"workers"`
}

// Scenario describes a wkbench/v1 load scenario.
type Scenario struct {
	// Version is the scenario schema version and must currently be "wkbench/v1".
	Version string `json:"version" yaml:"version"`
	// Run contains run identity and lifecycle controls.
	Run RunConfig `json:"run" yaml:"run"`
	// Limits contains global safety limits for a run.
	Limits LimitsConfig `json:"limits" yaml:"limits"`
	// Identity describes generated users and device identities.
	Identity IdentityConfig `json:"identity" yaml:"identity"`
	// Online describes connection and online-session behavior.
	Online OnlineConfig `json:"online" yaml:"online"`
	// Channels contains channel profile definitions used by traffic phases.
	Channels ChannelProfilesConfig `json:"channels" yaml:"channels"`
	// Messages describes message traffic generated by the scenario.
	Messages MessageTrafficConfig `json:"messages" yaml:"messages"`
}

// RunConfig contains run identity and common execution controls.
type RunConfig struct {
	// ID is the stable benchmark run identifier.
	ID string `json:"id" yaml:"id"`
	// Duration is the active load duration.
	Duration time.Duration `json:"duration" yaml:"duration"`
	// RampUp is the optional warm-up period before full load.
	RampUp time.Duration `json:"ramp_up" yaml:"ramp_up"`
	// RandomSeed makes generated scenario data reproducible when non-zero.
	RandomSeed int64 `json:"random_seed" yaml:"random_seed"`
	// FailFast stops the run after the first unrecoverable worker error.
	FailFast bool `json:"fail_fast" yaml:"fail_fast"`
	// ReportDir is the directory where reports should be written.
	ReportDir string `json:"report_dir" yaml:"report_dir"`
}

// LimitsConfig contains safety limits that cap generated workload size.
type LimitsConfig struct {
	// MaxUsers caps the number of identities created for a scenario.
	MaxUsers int `json:"max_users" yaml:"max_users"`
	// MaxChannels caps the number of channels created for a scenario.
	MaxChannels int `json:"max_channels" yaml:"max_channels"`
	// MaxConnections caps concurrent gateway connections.
	MaxConnections int `json:"max_connections" yaml:"max_connections"`
}

// IdentityConfig describes the generated benchmark user population.
type IdentityConfig struct {
	// Prefix is prepended to generated user IDs.
	Prefix string `json:"prefix" yaml:"prefix"`
	// Users is the number of generated users.
	Users int `json:"users" yaml:"users"`
	// DevicesPerUser is the number of simulated devices per generated user.
	DevicesPerUser int `json:"devices_per_user" yaml:"devices_per_user"`
}

// OnlineConfig describes simulated online-session behavior.
type OnlineConfig struct {
	// Connections is the target number of concurrently connected clients.
	Connections int `json:"connections" yaml:"connections"`
	// ConnectRate controls how quickly workers open gateway connections.
	ConnectRate Rate `json:"connect_rate" yaml:"connect_rate"`
	// KeepAliveInterval is the interval between keepalive frames.
	KeepAliveInterval time.Duration `json:"keepalive_interval" yaml:"keepalive_interval"`
}

// ChannelProfilesConfig groups channel profile definitions by shape.
type ChannelProfilesConfig struct {
	// Person contains one-to-one channel profile settings.
	Person ChannelProfile `json:"person" yaml:"person"`
	// Groups contains group-channel profile settings.
	Groups []ChannelProfile `json:"groups" yaml:"groups"`
}

// ChannelProfile describes a class of channels prepared for a scenario.
type ChannelProfile struct {
	// Name is a stable profile name referenced by traffic phases.
	Name string `json:"name" yaml:"name"`
	// Count is the number of channels created for this profile.
	Count int `json:"count" yaml:"count"`
	// SubscribersPerChannel is the target member count for each channel.
	SubscribersPerChannel int `json:"subscribers_per_channel" yaml:"subscribers_per_channel"`
}

// MessageTrafficConfig describes generated message traffic.
type MessageTrafficConfig struct {
	// Rate is the aggregate send rate for message traffic.
	Rate Rate `json:"rate" yaml:"rate"`
	// PayloadBytes is the generated message payload size in bytes.
	PayloadBytes int `json:"payload_bytes" yaml:"payload_bytes"`
	// Phases are optional traffic phase definitions.
	Phases []MessagePhase `json:"phases" yaml:"phases"`
}

// MessagePhase describes one named message traffic phase.
type MessagePhase struct {
	// Name is the phase identifier used in reports.
	Name string `json:"name" yaml:"name"`
	// Duration is how long this phase runs.
	Duration time.Duration `json:"duration" yaml:"duration"`
	// Rate overrides the scenario message rate for this phase when set.
	Rate Rate `json:"rate" yaml:"rate"`
	// ChannelProfile selects which channel profile receives this phase's messages.
	ChannelProfile string `json:"channel_profile" yaml:"channel_profile"`
}
