package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/WuKongIM/WuKongIM/pkg/flowdoc"
)

type commandMode string

const (
	modeReport commandMode = "report"
	modeCheck  commandMode = "check"
	modeRender commandMode = "render"
)

func (mode commandMode) valid() bool {
	return mode == modeReport || mode == modeCheck || mode == modeRender
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout io.Writer, stderr io.Writer) int {
	flags := flag.NewFlagSet("flowcheck", flag.ContinueOnError)
	flags.SetOutput(stderr)
	root := flags.String("root", ".", "repository root")
	modeValue := flags.String("mode", string(modeReport), "report, check, or render")
	writeIndex := flags.Bool(
		"write-index",
		false,
		"write the canonical index to docs/development/FLOW_INDEX.md",
	)
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if flags.NArg() != 0 {
		fmt.Fprintf(stderr, "flowcheck: unexpected arguments: %v\n", flags.Args())
		return 2
	}
	mode := commandMode(*modeValue)
	if !mode.valid() {
		fmt.Fprintf(stderr, "flowcheck: unsupported mode %q\n", mode)
		return 2
	}
	if *writeIndex && mode != modeRender {
		fmt.Fprintln(stderr, "flowcheck: --write-index requires --mode render")
		return 2
	}

	paths, err := discoverFlowFiles(*root)
	if err != nil {
		fmt.Fprintf(stderr, "flowcheck: %v\n", err)
		return 1
	}
	if mode == modeRender {
		var canonical bytes.Buffer
		if err := renderIndex(*root, paths, &canonical); err != nil {
			fmt.Fprintf(stderr, "flowcheck: %v\n", err)
			return 1
		}
		if *writeIndex {
			indexPath := filepath.Join(*root, "docs", "development", "FLOW_INDEX.md")
			if err := os.MkdirAll(filepath.Dir(indexPath), 0o755); err != nil {
				fmt.Fprintf(stderr, "flowcheck: create index directory: %v\n", err)
				return 1
			}
			if err := os.WriteFile(indexPath, canonical.Bytes(), 0o644); err != nil {
				fmt.Fprintf(stderr, "flowcheck: write index: %v\n", err)
				return 1
			}
			fmt.Fprintln(stdout, "flowcheck: wrote docs/development/FLOW_INDEX.md")
			return 0
		}
		if _, err := io.Copy(stdout, &canonical); err != nil {
			fmt.Fprintf(stderr, "flowcheck: write rendered index: %v\n", err)
			return 1
		}
		return 0
	}
	compliant := 0
	invalid := 0
	warnings := 0
	staleIndex := false
	for _, relative := range paths {
		content, err := os.ReadFile(filepath.Join(*root, filepath.FromSlash(relative)))
		if err != nil {
			fmt.Fprintf(stderr, "%s: %v\n", relative, err)
			invalid++
			continue
		}
		lines := physicalLineCount(content)
		if lines > 150 {
			fmt.Fprintf(
				stderr,
				"%s: %d lines exceeds the 150-line limit\n",
				relative,
				lines,
			)
			invalid++
			continue
		}
		if lines > 100 {
			fmt.Fprintf(
				stderr,
				"%s: %d lines exceeds the 100-line target\n",
				relative,
				lines,
			)
			warnings++
		}
		_, err = flowdoc.ParseMetadata(content)
		if err != nil {
			fmt.Fprintf(stderr, "%s: %v\n", relative, err)
			invalid++
			continue
		}
		if err := flowdoc.ValidateBody(content); err != nil {
			fmt.Fprintf(stderr, "%s: %v\n", relative, err)
			invalid++
			continue
		}
		readFirst, err := flowdoc.ReadFirstReferences(content)
		if err != nil || len(readFirst) < 1 || len(readFirst) > 5 {
			fmt.Fprintf(
				stderr,
				"%s: Read First must contain 1-5 local references\n",
				relative,
			)
			invalid++
			continue
		}
		if err := validateLocalReferences(*root, relative, content); err != nil {
			fmt.Fprintf(stderr, "%s: %v\n", relative, err)
			invalid++
			continue
		}
		compliant++
	}
	compareIndex := (mode == modeReport || mode == modeCheck) && invalid == 0
	if compareIndex {
		var canonical bytes.Buffer
		if err := renderIndex(*root, paths, &canonical); err != nil {
			if mode == modeCheck {
				fmt.Fprintf(stderr, "flowcheck: %v\n", err)
				return 1
			}
		} else {
			indexPath := filepath.Join(*root, "docs", "development", "FLOW_INDEX.md")
			current, err := os.ReadFile(indexPath)
			if err != nil || !bytes.Equal(current, canonical.Bytes()) {
				fmt.Fprintln(
					stderr,
					"docs/development/FLOW_INDEX.md: generated index is missing or stale",
				)
				staleIndex = true
			}
		}
	}
	fmt.Fprintf(
		stdout,
		"flowcheck: %d %s; %d compliant; %d invalid; %d warnings\n",
		len(paths),
		pluralize(len(paths), "FLOW file", "FLOW files"),
		compliant,
		invalid,
		warnings,
	)
	if mode == modeCheck && (invalid != 0 || staleIndex) {
		return 1
	}
	return 0
}

func renderIndex(root string, paths []string, output io.Writer) error {
	fmt.Fprintln(output, "<!-- Code generated by flowcheck; DO NOT EDIT. -->")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "# FLOW Index")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "This file is generated from repository FLOW.md metadata.")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "Regenerate with `GOWORK=off go run ./scripts/flowcheck --mode render --write-index`.")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "| Path | Scope | Summary | Lines | Budget |")
	fmt.Fprintln(output, "| --- | --- | --- | ---: | --- |")
	for _, relative := range paths {
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(relative)))
		if err != nil {
			return fmt.Errorf("%s: %w", relative, err)
		}
		metadata, err := flowdoc.ParseMetadata(content)
		if err != nil {
			return fmt.Errorf("%s: %w", relative, err)
		}
		scope := string(metadata.Scope)
		summary := metadata.Summary
		lines := physicalLineCount(content)
		budget := "ok"
		if lines > 150 {
			budget = "error"
		} else if lines > 100 {
			budget = "warning"
		}
		link := strings.ReplaceAll(relative, " ", "%20")
		summary = strings.ReplaceAll(summary, "|", "\\|")
		fmt.Fprintf(
			output,
			"| [%s](../../%s) | `%s` | %s | %d | %s |\n",
			relative,
			link,
			scope,
			summary,
			lines,
			budget,
		)
	}
	return nil
}

func physicalLineCount(content []byte) int {
	if len(content) == 0 {
		return 0
	}
	lines := bytes.Count(content, []byte{'\n'})
	if content[len(content)-1] != '\n' {
		lines++
	}
	return lines
}

func validateLocalReferences(root string, flowPath string, content []byte) error {
	references, err := flowdoc.LocalReferences(content)
	if err != nil {
		return err
	}
	rootAbsolute, err := filepath.Abs(root)
	if err != nil {
		return errors.New("resolve repository root")
	}
	rootAbsolute, err = filepath.EvalSymlinks(rootAbsolute)
	if err != nil {
		return errors.New("resolve repository root symlinks")
	}
	for _, reference := range references {
		if filepath.IsAbs(filepath.FromSlash(reference)) || strings.HasPrefix(reference, "/") {
			return fmt.Errorf("local reference %q must be relative", reference)
		}
		candidate := filepath.Join(
			rootAbsolute,
			filepath.FromSlash(filepath.Dir(flowPath)),
			filepath.FromSlash(reference),
		)
		inside, err := filepath.Rel(rootAbsolute, candidate)
		if err != nil || inside == ".." || strings.HasPrefix(inside, ".."+string(filepath.Separator)) {
			return fmt.Errorf("local reference %q escapes the repository", reference)
		}
		resolved, err := filepath.EvalSymlinks(candidate)
		if err != nil {
			if os.IsNotExist(err) {
				return fmt.Errorf("local reference %q does not exist", reference)
			}
			return fmt.Errorf("local reference %q: %w", reference, err)
		}
		inside, err = filepath.Rel(rootAbsolute, resolved)
		if err != nil || inside == ".." || strings.HasPrefix(inside, ".."+string(filepath.Separator)) {
			return fmt.Errorf("local reference %q escapes the repository through a symlink", reference)
		}
	}
	return nil
}

func discoverFlowFiles(root string) ([]string, error) {
	var result []string
	err := fs.WalkDir(os.DirFS(root), ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() && path != "." && ignoredDirectory(entry.Name()) {
			return fs.SkipDir
		}
		if entry.Type().IsRegular() && entry.Name() == "FLOW.md" {
			result = append(result, filepath.ToSlash(path))
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(result)
	return result, nil
}

func ignoredDirectory(name string) bool {
	switch name {
	case ".git", ".worktrees", "node_modules", "vendor", "tmp":
		return true
	default:
		return false
	}
}

func pluralize(count int, singular string, plural string) string {
	if count == 1 {
		return singular
	}
	return plural
}
