import type { ClusterMonitorMetricKey, ClusterMonitorStage, ClusterMonitorTone } from "./types"

type ClusterMonitorMetricConfig = {
  titleId: string
  helpId: string
  chartColor: string
  precision: number
  stage: ClusterMonitorStage
  tone: ClusterMonitorTone
}

export const clusterMonitorMetricConfig: Record<ClusterMonitorMetricKey, ClusterMonitorMetricConfig> = {
  controllerApplyGap: {
    titleId: "clusterMonitor.metrics.controllerApplyGap",
    helpId: "clusterMonitor.help.controllerApplyGap",
    chartColor: "#1d4ed8",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  controllerRaftStepQueueUsage: {
    titleId: "clusterMonitor.metrics.controllerRaftStepQueueUsage",
    helpId: "clusterMonitor.help.controllerRaftStepQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  controllerRaftStepEnqueueLatencyP99: {
    titleId: "clusterMonitor.metrics.controllerRaftStepEnqueueLatencyP99",
    helpId: "clusterMonitor.help.controllerRaftStepEnqueueLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  controllerRaftStepEnqueueErrorRate: {
    titleId: "clusterMonitor.metrics.controllerRaftStepEnqueueErrorRate",
    helpId: "clusterMonitor.help.controllerRaftStepEnqueueErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "runtimePressure",
    tone: "critical",
  },
  controllerStateRevision: {
    titleId: "clusterMonitor.metrics.controllerStateRevision",
    helpId: "clusterMonitor.help.controllerStateRevision",
    chartColor: "#2563eb",
    precision: 0,
    stage: "controlPlane",
    tone: "normal",
  },
  controllerActiveTasks: {
    titleId: "clusterMonitor.metrics.controllerActiveTasks",
    helpId: "clusterMonitor.help.controllerActiveTasks",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  controllerFailedTasks: {
    titleId: "clusterMonitor.metrics.controllerFailedTasks",
    helpId: "clusterMonitor.help.controllerFailedTasks",
    chartColor: "#be123c",
    precision: 0,
    stage: "incidentClosure",
    tone: "critical",
  },
  controllerNodesUnhealthy: {
    titleId: "clusterMonitor.metrics.controllerNodesUnhealthy",
    helpId: "clusterMonitor.help.controllerNodesUnhealthy",
    chartColor: "#dc2626",
    precision: 0,
    stage: "incidentClosure",
    tone: "critical",
  },
  controllerSlotLeaderSkew: {
    titleId: "clusterMonitor.metrics.controllerSlotLeaderSkew",
    helpId: "clusterMonitor.help.controllerSlotLeaderSkew",
    chartColor: "#d97706",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  controllerLeaderPresent: {
    titleId: "clusterMonitor.metrics.controllerLeaderPresent",
    helpId: "clusterMonitor.help.controllerLeaderPresent",
    chartColor: "#16a34a",
    precision: 0,
    stage: "controlPlane",
    tone: "normal",
  },
  slotLeaderStability: {
    titleId: "clusterMonitor.metrics.slotLeaderStability",
    helpId: "clusterMonitor.help.slotLeaderStability",
    chartColor: "#0f766e",
    precision: 2,
    stage: "slotReplication",
    tone: "normal",
  },
  slotProposeRate: {
    titleId: "clusterMonitor.metrics.slotProposeRate",
    helpId: "clusterMonitor.help.slotProposeRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "slotReplication",
    tone: "normal",
  },
  slotApplyGap: {
    titleId: "clusterMonitor.metrics.slotApplyGap",
    helpId: "clusterMonitor.help.slotApplyGap",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "slotReplication",
    tone: "warning",
  },
  slotLatencyP99: {
    titleId: "clusterMonitor.metrics.slotLatencyP99",
    helpId: "clusterMonitor.help.slotLatencyP99",
    chartColor: "#16a34a",
    precision: 1,
    stage: "slotReplication",
    tone: "warning",
  },
  slotProposalAdmissionRejectRate: {
    titleId: "clusterMonitor.metrics.slotProposalAdmissionRejectRate",
    helpId: "clusterMonitor.help.slotProposalAdmissionRejectRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "slotReplication",
    tone: "critical",
  },
  slotLeaderChangeRate: {
    titleId: "clusterMonitor.metrics.slotLeaderChangeRate",
    helpId: "clusterMonitor.help.slotLeaderChangeRate",
    chartColor: "#d97706",
    precision: 2,
    stage: "slotReplication",
    tone: "warning",
  },
  slotReplicaLagMax: {
    titleId: "clusterMonitor.metrics.slotReplicaLagMax",
    helpId: "clusterMonitor.help.slotReplicaLagMax",
    chartColor: "#ca8a04",
    precision: 2,
    stage: "slotReplication",
    tone: "warning",
  },
  slotSchedulerQueueUsage: {
    titleId: "clusterMonitor.metrics.slotSchedulerQueueUsage",
    helpId: "clusterMonitor.help.slotSchedulerQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  slotSchedulerInflightUsage: {
    titleId: "clusterMonitor.metrics.slotSchedulerInflightUsage",
    helpId: "clusterMonitor.help.slotSchedulerInflightUsage",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  slotSchedulerTaskLatencyP99: {
    titleId: "clusterMonitor.metrics.slotSchedulerTaskLatencyP99",
    helpId: "clusterMonitor.help.slotSchedulerTaskLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelAppendLatencyP99: {
    titleId: "clusterMonitor.metrics.channelAppendLatencyP99",
    helpId: "clusterMonitor.help.channelAppendLatencyP99",
    chartColor: "#22c55e",
    precision: 1,
    stage: "channelReplication",
    tone: "normal",
  },
  activeChannels: {
    titleId: "clusterMonitor.metrics.activeChannels",
    helpId: "clusterMonitor.help.activeChannels",
    chartColor: "#0d9488",
    precision: 0,
    stage: "channelReplication",
    tone: "normal",
  },
  channelAppendBatchRecordsP95: {
    titleId: "clusterMonitor.metrics.channelAppendBatchRecordsP95",
    helpId: "clusterMonitor.help.channelAppendBatchRecordsP95",
    chartColor: "#2563eb",
    precision: 0,
    stage: "channelReplication",
    tone: "normal",
  },
  channelAppendBatchBytesP95: {
    titleId: "clusterMonitor.metrics.channelAppendBatchBytesP95",
    helpId: "clusterMonitor.help.channelAppendBatchBytesP95",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "channelReplication",
    tone: "normal",
  },
  channelAppendErrorRate: {
    titleId: "clusterMonitor.metrics.channelAppendErrorRate",
    helpId: "clusterMonitor.help.channelAppendErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "channelReplication",
    tone: "critical",
  },
  channelWriterAdmissionUsage: {
    titleId: "clusterMonitor.metrics.channelWriterAdmissionUsage",
    helpId: "clusterMonitor.help.channelWriterAdmissionUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelRuntimeFollowersParked: {
    titleId: "clusterMonitor.metrics.channelRuntimeFollowersParked",
    helpId: "clusterMonitor.help.channelRuntimeFollowersParked",
    chartColor: "#d97706",
    precision: 0,
    stage: "channelReplication",
    tone: "warning",
  },
  channelActivationRejectRate: {
    titleId: "clusterMonitor.metrics.channelActivationRejectRate",
    helpId: "clusterMonitor.help.channelActivationRejectRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "channelReplication",
    tone: "critical",
  },
  channelReactorMailboxDepth: {
    titleId: "clusterMonitor.metrics.channelReactorMailboxDepth",
    helpId: "clusterMonitor.help.channelReactorMailboxDepth",
    chartColor: "#ea580c",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelWorkerQueueDepth: {
    titleId: "clusterMonitor.metrics.channelWorkerQueueDepth",
    helpId: "clusterMonitor.help.channelWorkerQueueDepth",
    chartColor: "#f97316",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelPullHintErrorRate: {
    titleId: "clusterMonitor.metrics.channelPullHintErrorRate",
    helpId: "clusterMonitor.help.channelPullHintErrorRate",
    chartColor: "#be123c",
    precision: 2,
    stage: "channelReplication",
    tone: "critical",
  },
  channelReplicationLatencyP99: {
    titleId: "clusterMonitor.metrics.channelReplicationLatencyP99",
    helpId: "clusterMonitor.help.channelReplicationLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "channelReplication",
    tone: "warning",
  },
  internalTraffic: {
    titleId: "clusterMonitor.metrics.internalTraffic",
    helpId: "clusterMonitor.help.internalTraffic",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  internalTxTraffic: {
    titleId: "clusterMonitor.metrics.internalTxTraffic",
    helpId: "clusterMonitor.help.internalTxTraffic",
    chartColor: "#0891b2",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  internalRxTraffic: {
    titleId: "clusterMonitor.metrics.internalRxTraffic",
    helpId: "clusterMonitor.help.internalRxTraffic",
    chartColor: "#0d9488",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcRate: {
    titleId: "clusterMonitor.metrics.rpcRate",
    helpId: "clusterMonitor.help.rpcRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcSuccessRate: {
    titleId: "clusterMonitor.metrics.rpcSuccessRate",
    helpId: "clusterMonitor.help.rpcSuccessRate",
    chartColor: "#0284c7",
    precision: 2,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcErrorRate: {
    titleId: "clusterMonitor.metrics.rpcErrorRate",
    helpId: "clusterMonitor.help.rpcErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "internalNetwork",
    tone: "critical",
  },
  rpcInflight: {
    titleId: "clusterMonitor.metrics.rpcInflight",
    helpId: "clusterMonitor.help.rpcInflight",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "internalNetwork",
    tone: "warning",
  },
  rpcLatencyP95: {
    titleId: "clusterMonitor.metrics.rpcLatencyP95",
    helpId: "clusterMonitor.help.rpcLatencyP95",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  rpcLatencyP99: {
    titleId: "clusterMonitor.metrics.rpcLatencyP99",
    helpId: "clusterMonitor.help.rpcLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  dialSuccessRate: {
    titleId: "clusterMonitor.metrics.dialSuccessRate",
    helpId: "clusterMonitor.help.dialSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "internalNetwork",
    tone: "normal",
  },
  dialLatencyP95: {
    titleId: "clusterMonitor.metrics.dialLatencyP95",
    helpId: "clusterMonitor.help.dialLatencyP95",
    chartColor: "#d97706",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  internalTransportQueueUsage: {
    titleId: "clusterMonitor.metrics.internalTransportQueueUsage",
    helpId: "clusterMonitor.help.internalTransportQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  internalTransportAdmissionErrorRate: {
    titleId: "clusterMonitor.metrics.internalTransportAdmissionErrorRate",
    helpId: "clusterMonitor.help.internalTransportAdmissionErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "runtimePressure",
    tone: "critical",
  },
  workqueuePressure: {
    titleId: "clusterMonitor.metrics.workqueuePressure",
    helpId: "clusterMonitor.help.workqueuePressure",
    chartColor: "#d97706",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeCpuPercent: {
    titleId: "clusterMonitor.metrics.nodeCpuPercent",
    helpId: "clusterMonitor.help.nodeCpuPercent",
    chartColor: "#dc2626",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeMemoryRSS: {
    titleId: "clusterMonitor.metrics.nodeMemoryRSS",
    helpId: "clusterMonitor.help.nodeMemoryRSS",
    chartColor: "#0f766e",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGoroutines: {
    titleId: "clusterMonitor.metrics.nodeGoroutines",
    helpId: "clusterMonitor.help.nodeGoroutines",
    chartColor: "#475569",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  goroutineProcessHistory: {
    titleId: "clusterMonitor.metrics.goroutineProcessHistory",
    helpId: "clusterMonitor.help.goroutineProcessHistory",
    chartColor: "#475569",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  goroutineModuleHistory: {
    titleId: "clusterMonitor.metrics.goroutineModuleHistory",
    helpId: "clusterMonitor.help.goroutineModuleHistory",
    chartColor: "#2563eb",
    precision: 0,
    stage: "runtimePressure",
    tone: "normal",
  },
  nodeGCPauseRate: {
    titleId: "clusterMonitor.metrics.nodeGCPauseRate",
    helpId: "clusterMonitor.help.nodeGCPauseRate",
    chartColor: "#be123c",
    precision: 2,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGCRate: {
    titleId: "clusterMonitor.metrics.nodeGCRate",
    helpId: "clusterMonitor.help.nodeGCRate",
    chartColor: "#ca8a04",
    precision: 2,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGCCPUFraction: {
    titleId: "clusterMonitor.metrics.nodeGCCPUFraction",
    helpId: "clusterMonitor.help.nodeGCCPUFraction",
    chartColor: "#7c3aed",
    precision: 2,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGCHeapGoalUsage: {
    titleId: "clusterMonitor.metrics.nodeGCHeapGoalUsage",
    helpId: "clusterMonitor.help.nodeGCHeapGoalUsage",
    chartColor: "#0891b2",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageWriteP99: {
    titleId: "clusterMonitor.metrics.storageWriteP99",
    helpId: "clusterMonitor.help.storageWriteP99",
    chartColor: "#db2777",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageCommitErrorRate: {
    titleId: "clusterMonitor.metrics.storageCommitErrorRate",
    helpId: "clusterMonitor.help.storageCommitErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "incidentClosure",
    tone: "critical",
  },
  storageCommitQueueUsage: {
    titleId: "clusterMonitor.metrics.storageCommitQueueUsage",
    helpId: "clusterMonitor.help.storageCommitQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storagePhysicalCommitP99: {
    titleId: "clusterMonitor.metrics.storagePhysicalCommitP99",
    helpId: "clusterMonitor.help.storagePhysicalCommitP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageCommitBatchRecordsP95: {
    titleId: "clusterMonitor.metrics.storageCommitBatchRecordsP95",
    helpId: "clusterMonitor.help.storageCommitBatchRecordsP95",
    chartColor: "#2563eb",
    precision: 0,
    stage: "runtimePressure",
    tone: "normal",
  },
  storageCommitBatchBytesP95: {
    titleId: "clusterMonitor.metrics.storageCommitBatchBytesP95",
    helpId: "clusterMonitor.help.storageCommitBatchBytesP95",
    chartColor: "#0d9488",
    precision: 1,
    stage: "runtimePressure",
    tone: "normal",
  },
  storagePebbleDiskUsage: {
    titleId: "clusterMonitor.metrics.storagePebbleDiskUsage",
    helpId: "clusterMonitor.help.storagePebbleDiskUsage",
    chartColor: "#be185d",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storagePebbleReadAmplification: {
    titleId: "clusterMonitor.metrics.storagePebbleReadAmplification",
    helpId: "clusterMonitor.help.storagePebbleReadAmplification",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storagePebbleCompactionDebt: {
    titleId: "clusterMonitor.metrics.storagePebbleCompactionDebt",
    helpId: "clusterMonitor.help.storagePebbleCompactionDebt",
    chartColor: "#7c2d12",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  sendRate: {
    titleId: "monitor.metrics.sendRate",
    helpId: "monitor.help.sendRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  sendSuccessRate: {
    titleId: "monitor.metrics.sendSuccessRate",
    helpId: "monitor.help.sendSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "sendEntry",
    tone: "normal",
  },
  entryLatencyP99: {
    titleId: "monitor.metrics.entryLatencyP99",
    helpId: "monitor.help.entryLatencyP99",
    chartColor: "#d97706",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  messageSendRate: {
    titleId: "monitor.metrics.messageSendRate",
    helpId: "monitor.help.messageSendRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  messageSendackErrorRate: {
    titleId: "monitor.metrics.messageSendackErrorRate",
    helpId: "monitor.help.messageSendackErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  sendQueueUsage: {
    titleId: "monitor.metrics.sendQueueUsage",
    helpId: "monitor.help.sendQueueUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  connectionOpenRate: {
    titleId: "monitor.metrics.connectionOpenRate",
    helpId: "monitor.help.connectionOpenRate",
    chartColor: "#0284c7",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  connectionCloseRate: {
    titleId: "monitor.metrics.connectionCloseRate",
    helpId: "monitor.help.connectionCloseRate",
    chartColor: "#ea580c",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  connectionCloseReasonRate: {
    titleId: "monitor.metrics.connectionCloseReasonRate",
    helpId: "monitor.help.connectionCloseReasonRate",
    chartColor: "#f97316",
    precision: 1,
    stage: "incidentClosure",
    tone: "warning",
  },
  authSuccessRate: {
    titleId: "monitor.metrics.authSuccessRate",
    helpId: "monitor.help.authSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "sendEntry",
    tone: "normal",
  },
  authLatencyP99: {
    titleId: "monitor.metrics.authLatencyP99",
    helpId: "monitor.help.authLatencyP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  sendackErrorRate: {
    titleId: "monitor.metrics.sendackErrorRate",
    helpId: "monitor.help.sendackErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "incidentClosure",
    tone: "critical",
  },
  gatewayInboundTraffic: {
    titleId: "monitor.metrics.gatewayInboundTraffic",
    helpId: "monitor.help.gatewayInboundTraffic",
    chartColor: "#0891b2",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  gatewayOutboundTraffic: {
    titleId: "monitor.metrics.gatewayOutboundTraffic",
    helpId: "monitor.help.gatewayOutboundTraffic",
    chartColor: "#0d9488",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  frameHandleLatencyP99: {
    titleId: "monitor.metrics.frameHandleLatencyP99",
    helpId: "monitor.help.frameHandleLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  asyncBatchWaitP99: {
    titleId: "monitor.metrics.asyncBatchWaitP99",
    helpId: "monitor.help.asyncBatchWaitP99",
    chartColor: "#d97706",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  asyncBatchRecordsP95: {
    titleId: "monitor.metrics.asyncBatchRecordsP95",
    helpId: "monitor.help.asyncBatchRecordsP95",
    chartColor: "#2563eb",
    precision: 0,
    stage: "sendEntry",
    tone: "normal",
  },
  asyncBatchBytesP95: {
    titleId: "monitor.metrics.asyncBatchBytesP95",
    helpId: "monitor.help.asyncBatchBytesP95",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  authQueueUsage: {
    titleId: "monitor.metrics.authQueueUsage",
    helpId: "monitor.help.authQueueUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  transportQueueUsage: {
    titleId: "monitor.metrics.transportQueueUsage",
    helpId: "monitor.help.transportQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  transportBytesUsage: {
    titleId: "monitor.metrics.transportBytesUsage",
    helpId: "monitor.help.transportBytesUsage",
    chartColor: "#dc2626",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  commitRate: {
    titleId: "monitor.metrics.commitRate",
    helpId: "monitor.help.commitRate",
    chartColor: "#0f766e",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  messageAppendErrorRate: {
    titleId: "monitor.metrics.messageAppendErrorRate",
    helpId: "monitor.help.messageAppendErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "appendCommit",
    tone: "critical",
  },
  messageAppendLatencyP95: {
    titleId: "monitor.metrics.messageAppendLatencyP95",
    helpId: "monitor.help.messageAppendLatencyP95",
    chartColor: "#9333ea",
    precision: 1,
    stage: "appendCommit",
    tone: "warning",
  },
  commitLatencyP99: {
    titleId: "monitor.metrics.commitLatencyP99",
    helpId: "monitor.help.commitLatencyP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  pendingCommitBacklog: {
    titleId: "monitor.metrics.pendingCommitBacklog",
    helpId: "monitor.help.pendingCommitBacklog",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "appendCommit",
    tone: "warning",
  },
  messageDispatchEnqueueRate: {
    titleId: "monitor.metrics.messageDispatchEnqueueRate",
    helpId: "monitor.help.messageDispatchEnqueueRate",
    chartColor: "#0d9488",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  messageDispatchOverflowRate: {
    titleId: "monitor.metrics.messageDispatchOverflowRate",
    helpId: "monitor.help.messageDispatchOverflowRate",
    chartColor: "#f97316",
    precision: 2,
    stage: "appendCommit",
    tone: "critical",
  },
  conversationSyncRate: {
    titleId: "monitor.metrics.conversationSyncRate",
    helpId: "monitor.help.conversationSyncRate",
    chartColor: "#0284c7",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationSyncLatencyP99: {
    titleId: "monitor.metrics.conversationSyncLatencyP99",
    helpId: "monitor.help.conversationSyncLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationSyncErrorRate: {
    titleId: "monitor.metrics.conversationSyncErrorRate",
    helpId: "monitor.help.conversationSyncErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "conversationSync",
    tone: "critical",
  },
  conversationReturnedItems: {
    titleId: "monitor.metrics.conversationReturnedItems",
    helpId: "monitor.help.conversationReturnedItems",
    chartColor: "#059669",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationRecentLoadLatencyP99: {
    titleId: "monitor.metrics.conversationRecentLoadLatencyP99",
    helpId: "monitor.help.conversationRecentLoadLatencyP99",
    chartColor: "#c026d3",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveDirtyRows: {
    titleId: "monitor.metrics.conversationActiveDirtyRows",
    helpId: "monitor.help.conversationActiveDirtyRows",
    chartColor: "#f59e0b",
    precision: 0,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveNormalRows: {
    titleId: "monitor.metrics.conversationActiveNormalRows",
    helpId: "monitor.help.conversationActiveNormalRows",
    chartColor: "#0f766e",
    precision: 0,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationActiveCMDRows: {
    titleId: "monitor.metrics.conversationActiveCMDRows",
    helpId: "monitor.help.conversationActiveCMDRows",
    chartColor: "#0891b2",
    precision: 0,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationActiveNormalDirtyRows: {
    titleId: "monitor.metrics.conversationActiveNormalDirtyRows",
    helpId: "monitor.help.conversationActiveNormalDirtyRows",
    chartColor: "#f97316",
    precision: 0,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveCMDDirtyRows: {
    titleId: "monitor.metrics.conversationActiveCMDDirtyRows",
    helpId: "monitor.help.conversationActiveCMDDirtyRows",
    chartColor: "#ea580c",
    precision: 0,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveOldestDirtyAge: {
    titleId: "monitor.metrics.conversationActiveOldestDirtyAge",
    helpId: "monitor.help.conversationActiveOldestDirtyAge",
    chartColor: "#d97706",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveFlushLatencyP99: {
    titleId: "monitor.metrics.conversationActiveFlushLatencyP99",
    helpId: "monitor.help.conversationActiveFlushLatencyP99",
    chartColor: "#0d9488",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveFlushErrorRate: {
    titleId: "monitor.metrics.conversationActiveFlushErrorRate",
    helpId: "monitor.help.conversationActiveFlushErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "conversationSync",
    tone: "critical",
  },
  conversationAuthorityPressureRate: {
    titleId: "monitor.metrics.conversationAuthorityPressureRate",
    helpId: "monitor.help.conversationAuthorityPressureRate",
    chartColor: "#4f46e5",
    precision: 2,
    stage: "conversationSync",
    tone: "warning",
  },
  deliveryRate: {
    titleId: "monitor.metrics.deliveryRate",
    helpId: "monitor.help.deliveryRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryLatencyP99: {
    titleId: "monitor.metrics.deliveryLatencyP99",
    helpId: "monitor.help.deliveryLatencyP99",
    chartColor: "#db2777",
    precision: 1,
    stage: "onlineDelivery",
    tone: "warning",
  },
  fanOutRatio: {
    titleId: "monitor.metrics.fanOutRatio",
    helpId: "monitor.help.fanOutRatio",
    chartColor: "#4f46e5",
    precision: 2,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryEnqueueRate: {
    titleId: "monitor.metrics.deliveryEnqueueRate",
    helpId: "monitor.help.deliveryEnqueueRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryQueueUsage: {
    titleId: "monitor.metrics.deliveryQueueUsage",
    helpId: "monitor.help.deliveryQueueUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "onlineDelivery",
    tone: "warning",
  },
  deliveryRetryRate: {
    titleId: "monitor.metrics.deliveryRetryRate",
    helpId: "monitor.help.deliveryRetryRate",
    chartColor: "#d97706",
    precision: 2,
    stage: "offlineRetry",
    tone: "warning",
  },
  deliveryAdmissionErrorRate: {
    titleId: "monitor.metrics.deliveryAdmissionErrorRate",
    helpId: "monitor.help.deliveryAdmissionErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "onlineDelivery",
    tone: "critical",
  },
  deliveryRouteExpireRate: {
    titleId: "monitor.metrics.deliveryRouteExpireRate",
    helpId: "monitor.help.deliveryRouteExpireRate",
    chartColor: "#be123c",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  offlineEnqueueRate: {
    titleId: "monitor.metrics.offlineEnqueueRate",
    helpId: "monitor.help.offlineEnqueueRate",
    chartColor: "#64748b",
    precision: 1,
    stage: "offlineRetry",
    tone: "normal",
  },
  retryQueueDepth: {
    titleId: "monitor.metrics.retryQueueDepth",
    helpId: "monitor.help.retryQueueDepth",
    chartColor: "#ea580c",
    precision: 0,
    stage: "offlineRetry",
    tone: "warning",
  },
  pathErrorRate: {
    titleId: "monitor.metrics.pathErrorRate",
    helpId: "monitor.help.pathErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  activeConnections: {
    titleId: "monitor.metrics.onlineConnections",
    helpId: "monitor.help.onlineConnections",
    chartColor: "#0d9488",
    precision: 0,
    stage: "sendEntry",
    tone: "normal",
  },
}

export const clusterMonitorStageLabelIds: Record<ClusterMonitorStage, string> = {
  controlPlane: "clusterMonitor.stage.controlPlane",
  slotReplication: "clusterMonitor.stage.slotReplication",
  channelReplication: "clusterMonitor.stage.channelReplication",
  internalNetwork: "clusterMonitor.stage.internalNetwork",
  runtimePressure: "clusterMonitor.stage.runtimePressure",
  incidentClosure: "clusterMonitor.stage.incidentClosure",
  sendEntry: "monitor.stage.sendEntry",
  appendCommit: "monitor.stage.appendCommit",
  conversationSync: "monitor.stage.conversationSync",
  onlineDelivery: "monitor.stage.onlineDelivery",
  offlineRetry: "monitor.stage.offlineRetry",
  errorClosure: "monitor.stage.errorClosure",
}

export const clusterMonitorStatusByTone: Record<ClusterMonitorTone, string> = {
  normal: "clusterMonitor.status.normal",
  warning: "clusterMonitor.status.warning",
  critical: "clusterMonitor.status.critical",
  preview: "clusterMonitor.status.preview",
}

export const clusterMonitorSnapshotLabelIds: Record<string, string> = {
  goroutineProcessTotal: "clusterMonitor.goroutines.processTotal",
  goroutineManagedTotal: "clusterMonitor.goroutines.managedTotal",
  goroutineUnmanagedTotal: "clusterMonitor.goroutines.unmanagedTotal",
  goroutinePanicTotal: "clusterMonitor.goroutines.panicTotal",
  goroutineSaturatedPools: "clusterMonitor.goroutines.saturatedPools",
  nodesAlive: "clusterMonitor.snapshot.nodesAlive",
  slotsReady: "clusterMonitor.snapshot.slotsReady",
  controllerApplyGap: "clusterMonitor.snapshot.controllerApplyGap",
  rpcErrorRate: "clusterMonitor.snapshot.rpcErrorRate",
  queuePressure: "clusterMonitor.snapshot.queuePressure",
  storageWriteP99: "clusterMonitor.snapshot.storageWriteP99",
  send: "monitor.snapshot.send",
  delivery: "monitor.snapshot.delivery",
  entryP99: "monitor.snapshot.entryP99",
  conversationSyncP99: "monitor.snapshot.conversationSyncP99",
  conversationSyncErrors: "monitor.snapshot.conversationSyncErrors",
  conversationDirtyAge: "monitor.snapshot.conversationDirtyAge",
  conversationFlushErrors: "monitor.snapshot.conversationFlushErrors",
  deliveryP99: "monitor.snapshot.deliveryP99",
  errors: "monitor.snapshot.errors",
  retryDepth: "monitor.snapshot.retryDepth",
  online: "monitor.snapshot.online",
}

export const clusterMonitorStatLabelIds: Record<string, string> = {
  avg: "clusterMonitor.stat.avg",
  min: "clusterMonitor.stat.min",
  peak: "clusterMonitor.stat.peak",
  total: "monitor.stat.total",
  latest: "clusterMonitor.stat.latest",
  rejected: "clusterMonitor.stat.rejected",
  p95Gap: "clusterMonitor.stat.p95Gap",
  maxGap: "clusterMonitor.stat.maxGap",
  slowNodes: "clusterMonitor.stat.slowNodes",
  leaderMissing: "clusterMonitor.stat.leaderMissing",
  quorumLost: "clusterMonitor.stat.quorumLost",
  transfers: "clusterMonitor.stat.transfers",
  p50: "clusterMonitor.stat.p50",
  p95: "clusterMonitor.stat.p95",
  laggingSlots: "clusterMonitor.stat.laggingSlots",
  isrInsufficient: "clusterMonitor.stat.isrInsufficient",
  noLeader: "clusterMonitor.stat.noLeader",
  affectedChannels: "clusterMonitor.stat.affectedChannels",
  slowAppends: "clusterMonitor.stat.slowAppends",
  tx: "clusterMonitor.stat.tx",
  rx: "clusterMonitor.stat.rx",
  callsPerSecond: "clusterMonitor.stat.callsPerSecond",
  errorsPerSecond: "clusterMonitor.stat.errorsPerSecond",
  timeouts: "clusterMonitor.stat.timeouts",
  inflight: "clusterMonitor.stat.inflight",
  busy: "clusterMonitor.stat.busy",
  critical: "clusterMonitor.stat.critical",
  queueFull: "clusterMonitor.stat.queueFull",
  flushWait: "clusterMonitor.stat.flushWait",
  warning: "clusterMonitor.stat.warning",
  topReason: "clusterMonitor.stat.topReason",
  unavailableReason: "clusterMonitor.stat.unavailableReason",
}
