import type { ClusterMonitorMetricKey, ClusterMonitorStage, ClusterMonitorTone } from "./types"

type ClusterMonitorMetricConfig = {
  titleId: string
  helpId: string
  chartColor: string
  precision: number
  stage: ClusterMonitorStage
  tone: ClusterMonitorTone
}

const clusterMonitorHealthMetrics: ReadonlySet<ClusterMonitorMetricKey> = new Set([
  "activeConnections",
  "activeChannels",
  "channelISRAnomalies",
  "channelStoreOwnership",
  "controllerApplyGap",
  "controllerLeaderPresent",
  "controllerOldestTaskAge",
  "controllerRaftMembership",
  "controllerStateRevision",
  "nodeHealthFreshness",
  "nodeHealthReportAge",
  "nodeLifecycleState",
  "slotApplyGap",
  "slotLeaderStability",
  "slotReplicaLagMax",
])

const clusterMonitorPressureMetrics: ReadonlySet<ClusterMonitorMetricKey> = new Set([
  "authQueueUsage",
  "channelReactorMailboxDepth",
  "channelWorkerQueueDepth",
  "deliveryQueueUsage",
  "sendQueueUsage",
  "internalTransportQueueUsage",
  "rpcInflight",
  "slotSchedulerInflightUsage",
  "slotSchedulerQueueUsage",
  "storageCommitQueueUsage",
  "transportBytesUsage",
  "transportQueueUsage",
])

const clusterMonitorLatencyMetrics: ReadonlySet<ClusterMonitorMetricKey> = new Set([
  "asyncBatchWaitP99",
  "authLatencyP99",
  "channelAppendBatchWaitP99",
  "channelAppendLatencyP99",
  "channelExecutionMailboxWaitP99",
  "channelPullLatencyP99",
  "channelReplicationLatencyP99",
  "channelRouterLatencyP99",
  "commitLatencyP99",
  "conversationDirectoryLatencyP99",
  "conversationHydrationLatencyP99",
  "controllerDecisionLatencyP99",
  "controllerRaftStepEnqueueLatencyP99",
  "controllerVoterPromotionLatencyP99",
  "deliveryLatencyP99",
  "deliveryRecipientAdmissionWaitP99",
  "dialLatencyP95",
  "entryLatencyP99",
  "frameHandleLatencyP99",
  "gatewayTransportWriteLatencyP99",
  "messageAppendLatencyP95",
  "messageCommittedReplayLatencyP99",
  "messageEventStageLatencyP99",
  "messageSendBatchStageLatencyP99",
  "presenceEndpointLookupLatencyP99",
  "presenceMaintenanceLatencyP99",
  "rpcClientLatencyP99",
  "rpcLatencyP95",
  "rpcLatencyP99",
  "runtimePoolTaskP99",
  "runtimePoolWaitP99",
  "slotLatencyP99",
  "slotPreferredLeaderWaitP99",
  "slotReplicaMoveLatencyP99",
  "slotReplicaMovePhaseLatencyP99",
  "slotSchedulerTaskLatencyP99",
  "storagePhysicalCommitP99",
  "storageWriteP99",
])

function importantMetric(
  key: ClusterMonitorMetricKey,
  stage: ClusterMonitorStage,
  tone: ClusterMonitorTone,
  precision = 1,
): ClusterMonitorMetricConfig {
  const colors: Record<ClusterMonitorTone, string> = {
    normal: "#0891b2",
    warning: "#d97706",
    critical: "#dc2626",
    preview: "#64748b",
  }
  return {
    titleId: `clusterMonitor.metrics.${key}`,
    helpId: "clusterMonitor.help.importantMetric",
    chartColor: colors[tone],
    precision,
    stage,
    tone,
  }
}

export function clusterMonitorMetricOperationalPriority(key: ClusterMonitorMetricKey): number {
  const config = clusterMonitorMetricConfig[key]
  if (clusterMonitorHealthMetrics.has(key)) return 0
  if (config.tone === "critical") return 1
  if (clusterMonitorLatencyMetrics.has(key)) return 3
  if (config.stage === "runtimePressure" || clusterMonitorPressureMetrics.has(key)) return 2
  return 4
}

export const clusterMonitorMetricConfig: Record<ClusterMonitorMetricKey, ClusterMonitorMetricConfig> = {
  gatewayDeliveryRate: importantMetric("gatewayDeliveryRate", "sendEntry", "normal"),
  gatewayTransportWriteLatencyP99: importantMetric("gatewayTransportWriteLatencyP99", "sendEntry", "warning"),
  rpcClientErrorRate: importantMetric("rpcClientErrorRate", "incidentClosure", "critical", 2),
  rpcClientLatencyP99: importantMetric("rpcClientLatencyP99", "internalNetwork", "warning"),
  transportEnqueueErrorRate: importantMetric("transportEnqueueErrorRate", "runtimePressure", "critical", 2),
  transportConnectionPool: importantMetric("transportConnectionPool", "internalNetwork", "warning", 0),
  transportWriteBatchFrames: importantMetric("transportWriteBatchFrames", "internalNetwork", "normal"),
  messageAppendErrorBreakdown: importantMetric("messageAppendErrorBreakdown", "errorClosure", "critical", 2),
  messageSendBatchStageLatencyP99: importantMetric("messageSendBatchStageLatencyP99", "appendCommit", "warning"),
  messageEventRate: importantMetric("messageEventRate", "appendCommit", "normal"),
  messageEventErrorRate: importantMetric("messageEventErrorRate", "errorClosure", "critical", 2),
  messageEventStageLatencyP99: importantMetric("messageEventStageLatencyP99", "appendCommit", "warning"),
  messageEventStreamCacheUsage: importantMetric("messageEventStreamCacheUsage", "runtimePressure", "warning"),
  messageCommittedReplayLag: importantMetric("messageCommittedReplayLag", "offlineRetry", "warning", 0),
  messageCommittedReplayLatencyP99: importantMetric("messageCommittedReplayLatencyP99", "offlineRetry", "warning"),
  deliveryErrorRate: importantMetric("deliveryErrorRate", "errorClosure", "critical", 2),
  deliveryRecipientWorkerUsage: importantMetric("deliveryRecipientWorkerUsage", "runtimePressure", "warning"),
  deliveryRecipientAdmissionWaitP99: importantMetric("deliveryRecipientAdmissionWaitP99", "runtimePressure", "warning"),
  deliveryAckFailureRate: importantMetric("deliveryAckFailureRate", "errorClosure", "critical", 2),
  presenceEndpointLookupErrorRate: importantMetric("presenceEndpointLookupErrorRate", "errorClosure", "critical", 2),
  presenceEndpointLookupLatencyP99: importantMetric("presenceEndpointLookupLatencyP99", "onlineDelivery", "warning"),
  presenceMaintenanceErrorRate: importantMetric("presenceMaintenanceErrorRate", "errorClosure", "critical", 2),
  presenceMaintenanceLatencyP99: importantMetric("presenceMaintenanceLatencyP99", "onlineDelivery", "warning"),
  conversationHydrationErrorRate: importantMetric("conversationHydrationErrorRate", "incidentClosure", "critical", 2),
  conversationHydrationBatchItemsP95: importantMetric("conversationHydrationBatchItemsP95", "conversationSync", "normal", 0),
  channelCapacityUsage: importantMetric("channelCapacityUsage", "runtimePressure", "warning"),
  channelExecutionQueueDepth: importantMetric("channelExecutionQueueDepth", "runtimePressure", "warning", 0),
  channelExecutionWorkerBusy: importantMetric("channelExecutionWorkerBusy", "runtimePressure", "warning"),
  channelExecutionEnqueueErrorRate: importantMetric("channelExecutionEnqueueErrorRate", "incidentClosure", "critical", 2),
  channelExecutionMailboxWaitP99: importantMetric("channelExecutionMailboxWaitP99", "runtimePressure", "warning"),
  channelISRAnomalies: importantMetric("channelISRAnomalies", "incidentClosure", "critical", 0),
  channelWorkerQueueUsage: importantMetric("channelWorkerQueueUsage", "runtimePressure", "warning"),
  channelWorkerAdmissionErrorRate: importantMetric("channelWorkerAdmissionErrorRate", "incidentClosure", "critical", 2),
  channelPullErrorRate: importantMetric("channelPullErrorRate", "incidentClosure", "critical", 2),
  channelPullLatencyP99: importantMetric("channelPullLatencyP99", "channelReplication", "warning"),
  channelPendingMeta: importantMetric("channelPendingMeta", "channelReplication", "warning", 0),
  channelMetaCreateQueueDepth: importantMetric("channelMetaCreateQueueDepth", "runtimePressure", "warning", 0),
  channelMetaCreateErrorRate: importantMetric("channelMetaCreateErrorRate", "incidentClosure", "critical", 2),
  channelAppendBatchWaitP99: importantMetric("channelAppendBatchWaitP99", "channelReplication", "warning"),
  channelRouterGroupUsage: importantMetric("channelRouterGroupUsage", "runtimePressure", "warning"),
  channelRouterErrorRate: importantMetric("channelRouterErrorRate", "incidentClosure", "critical", 2),
  channelRouterLatencyP99: importantMetric("channelRouterLatencyP99", "channelReplication", "warning"),
  channelPostCommitHandoffUsage: importantMetric("channelPostCommitHandoffUsage", "runtimePressure", "warning"),
  channelPostCommitRetryDepth: importantMetric("channelPostCommitRetryDepth", "incidentClosure", "critical", 0),
  channelEffectPoolUsage: importantMetric("channelEffectPoolUsage", "runtimePressure", "warning"),
  channelEffectErrorRate: importantMetric("channelEffectErrorRate", "incidentClosure", "critical", 2),
  storageMemtableUsage: importantMetric("storageMemtableUsage", "runtimePressure", "warning", 0),
  storageWALPhysicalSize: importantMetric("storageWALPhysicalSize", "runtimePressure", "warning", 0),
  storageSSTSize: importantMetric("storageSSTSize", "runtimePressure", "normal", 0),
  storageWALAmplification: importantMetric("storageWALAmplification", "runtimePressure", "warning", 2),
  storageFlushThroughput: importantMetric("storageFlushThroughput", "appendCommit", "normal"),
  storageCompactionReadThroughput: importantMetric("storageCompactionReadThroughput", "runtimePressure", "normal"),
  storageCompactionWriteThroughput: importantMetric("storageCompactionWriteThroughput", "runtimePressure", "normal"),
  storageBackgroundJobs: importantMetric("storageBackgroundJobs", "runtimePressure", "warning", 0),
  storageCompactionInflightBytes: importantMetric("storageCompactionInflightBytes", "runtimePressure", "warning", 0),
  channelStoreOwnership: importantMetric("channelStoreOwnership", "runtimePressure", "warning", 0),
  controllerDecisionRate: importantMetric("controllerDecisionRate", "controlPlane", "normal"),
  controllerDecisionLatencyP99: importantMetric("controllerDecisionLatencyP99", "controlPlane", "warning"),
  controllerOldestTaskAge: importantMetric("controllerOldestTaskAge", "incidentClosure", "critical"),
  controllerTaskFailureRate: importantMetric("controllerTaskFailureRate", "incidentClosure", "critical", 2),
  controllerMigrationsActive: importantMetric("controllerMigrationsActive", "controlPlane", "warning", 0),
  controllerMigrationFailureRate: importantMetric("controllerMigrationFailureRate", "incidentClosure", "critical", 2),
  controllerRaftMembership: importantMetric("controllerRaftMembership", "controlPlane", "warning", 0),
  controllerVoterPromotionRate: importantMetric("controllerVoterPromotionRate", "controlPlane", "normal"),
  controllerVoterPromotionBlockers: importantMetric("controllerVoterPromotionBlockers", "incidentClosure", "critical", 2),
  controllerVoterPromotionLatencyP99: importantMetric("controllerVoterPromotionLatencyP99", "controlPlane", "warning"),
  nodeLifecycleState: importantMetric("nodeLifecycleState", "controlPlane", "warning", 0),
  nodeHealthFreshness: importantMetric("nodeHealthFreshness", "controlPlane", "warning", 0),
  nodeHealthReportAge: importantMetric("nodeHealthReportAge", "incidentClosure", "critical"),
  nodeLifecycleFailureRate: importantMetric("nodeLifecycleFailureRate", "incidentClosure", "critical", 2),
  nodeLifecycleBlockers: importantMetric("nodeLifecycleBlockers", "incidentClosure", "critical", 0),
  slotPreferredLeaderReconcileRate: importantMetric("slotPreferredLeaderReconcileRate", "slotReplication", "normal"),
  slotPreferredLeaderWaitP99: importantMetric("slotPreferredLeaderWaitP99", "slotReplication", "warning"),
  slotReplicaMoveLatencyP99: importantMetric("slotReplicaMoveLatencyP99", "slotReplication", "warning"),
  slotReplicaMoveFailureRate: importantMetric("slotReplicaMoveFailureRate", "incidentClosure", "critical", 2),
  slotReplicaMovePhaseFailureRate: importantMetric("slotReplicaMovePhaseFailureRate", "incidentClosure", "critical", 2),
  slotReplicaMovePhaseLatencyP99: importantMetric("slotReplicaMovePhaseLatencyP99", "slotReplication", "warning"),
  nodeThreads: importantMetric("nodeThreads", "runtimePressure", "warning", 0),
  nodeAntsPoolUsage: importantMetric("nodeAntsPoolUsage", "runtimePressure", "warning"),
  nodeAntsPoolWaiting: importantMetric("nodeAntsPoolWaiting", "runtimePressure", "warning", 0),
  runtimePoolWaitP99: importantMetric("runtimePoolWaitP99", "runtimePressure", "warning"),
  runtimePoolTaskP99: importantMetric("runtimePoolTaskP99", "runtimePressure", "warning"),
  runtimePoolAdmissionErrorRate: importantMetric("runtimePoolAdmissionErrorRate", "incidentClosure", "critical", 2),
  runtimePoolInflightUsage: importantMetric("runtimePoolInflightUsage", "runtimePressure", "warning"),
  runtimePoolQueueBytesUsage: importantMetric("runtimePoolQueueBytesUsage", "runtimePressure", "warning"),
  diagnosticsBufferUsage: importantMetric("diagnosticsBufferUsage", "runtimePressure", "warning"),
  diagnosticsDroppedRate: importantMetric("diagnosticsDroppedRate", "incidentClosure", "critical", 2),
  goroutineStartRate: importantMetric("goroutineStartRate", "runtimePressure", "normal"),
  goroutinePanicRate: importantMetric("goroutinePanicRate", "incidentClosure", "critical", 2),
  goroutinePoolBusy: importantMetric("goroutinePoolBusy", "runtimePressure", "warning"),
  goroutinePoolQueueDepth: importantMetric("goroutinePoolQueueDepth", "runtimePressure", "warning", 0),
  goroutinePoolRejectionRate: importantMetric("goroutinePoolRejectionRate", "incidentClosure", "critical", 2),
  controllerApplyGap: {
    titleId: "clusterMonitor.metrics.controllerApplyGap",
    helpId: "clusterMonitor.help.controllerApplyGap",
    chartColor: "#1d4ed8",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  controllerRaftStepQueueUsage: {
    titleId: "clusterMonitor.metrics.controllerRaftStepQueueUsage",
    helpId: "clusterMonitor.help.controllerRaftStepQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  controllerRaftStepEnqueueLatencyP99: {
    titleId: "clusterMonitor.metrics.controllerRaftStepEnqueueLatencyP99",
    helpId: "clusterMonitor.help.controllerRaftStepEnqueueLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  controllerRaftStepEnqueueErrorRate: {
    titleId: "clusterMonitor.metrics.controllerRaftStepEnqueueErrorRate",
    helpId: "clusterMonitor.help.controllerRaftStepEnqueueErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "runtimePressure",
    tone: "critical",
  },
  controllerStateRevision: {
    titleId: "clusterMonitor.metrics.controllerStateRevision",
    helpId: "clusterMonitor.help.controllerStateRevision",
    chartColor: "#2563eb",
    precision: 0,
    stage: "controlPlane",
    tone: "normal",
  },
  controllerActiveTasks: {
    titleId: "clusterMonitor.metrics.controllerActiveTasks",
    helpId: "clusterMonitor.help.controllerActiveTasks",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  controllerFailedTasks: {
    titleId: "clusterMonitor.metrics.controllerFailedTasks",
    helpId: "clusterMonitor.help.controllerFailedTasks",
    chartColor: "#be123c",
    precision: 0,
    stage: "incidentClosure",
    tone: "critical",
  },
  controllerNodesUnhealthy: {
    titleId: "clusterMonitor.metrics.controllerNodesUnhealthy",
    helpId: "clusterMonitor.help.controllerNodesUnhealthy",
    chartColor: "#dc2626",
    precision: 0,
    stage: "incidentClosure",
    tone: "critical",
  },
  controllerSlotLeaderSkew: {
    titleId: "clusterMonitor.metrics.controllerSlotLeaderSkew",
    helpId: "clusterMonitor.help.controllerSlotLeaderSkew",
    chartColor: "#d97706",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  controllerLeaderPresent: {
    titleId: "clusterMonitor.metrics.controllerLeaderPresent",
    helpId: "clusterMonitor.help.controllerLeaderPresent",
    chartColor: "#16a34a",
    precision: 0,
    stage: "controlPlane",
    tone: "normal",
  },
  slotLeaderStability: {
    titleId: "clusterMonitor.metrics.slotLeaderStability",
    helpId: "clusterMonitor.help.slotLeaderStability",
    chartColor: "#0f766e",
    precision: 2,
    stage: "slotReplication",
    tone: "normal",
  },
  slotProposeRate: {
    titleId: "clusterMonitor.metrics.slotProposeRate",
    helpId: "clusterMonitor.help.slotProposeRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "slotReplication",
    tone: "normal",
  },
  slotApplyGap: {
    titleId: "clusterMonitor.metrics.slotApplyGap",
    helpId: "clusterMonitor.help.slotApplyGap",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "slotReplication",
    tone: "warning",
  },
  slotLatencyP99: {
    titleId: "clusterMonitor.metrics.slotLatencyP99",
    helpId: "clusterMonitor.help.slotLatencyP99",
    chartColor: "#16a34a",
    precision: 1,
    stage: "slotReplication",
    tone: "warning",
  },
  slotProposalAdmissionRejectRate: {
    titleId: "clusterMonitor.metrics.slotProposalAdmissionRejectRate",
    helpId: "clusterMonitor.help.slotProposalAdmissionRejectRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "slotReplication",
    tone: "critical",
  },
  slotLeaderChangeRate: {
    titleId: "clusterMonitor.metrics.slotLeaderChangeRate",
    helpId: "clusterMonitor.help.slotLeaderChangeRate",
    chartColor: "#d97706",
    precision: 2,
    stage: "slotReplication",
    tone: "warning",
  },
  slotReplicaLagMax: {
    titleId: "clusterMonitor.metrics.slotReplicaLagMax",
    helpId: "clusterMonitor.help.slotReplicaLagMax",
    chartColor: "#ca8a04",
    precision: 2,
    stage: "slotReplication",
    tone: "warning",
  },
  slotSchedulerQueueUsage: {
    titleId: "clusterMonitor.metrics.slotSchedulerQueueUsage",
    helpId: "clusterMonitor.help.slotSchedulerQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  slotSchedulerInflightUsage: {
    titleId: "clusterMonitor.metrics.slotSchedulerInflightUsage",
    helpId: "clusterMonitor.help.slotSchedulerInflightUsage",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  slotSchedulerTaskLatencyP99: {
    titleId: "clusterMonitor.metrics.slotSchedulerTaskLatencyP99",
    helpId: "clusterMonitor.help.slotSchedulerTaskLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelAppendLatencyP99: {
    titleId: "clusterMonitor.metrics.channelAppendLatencyP99",
    helpId: "clusterMonitor.help.channelAppendLatencyP99",
    chartColor: "#22c55e",
    precision: 1,
    stage: "channelReplication",
    tone: "normal",
  },
  activeChannels: {
    titleId: "clusterMonitor.metrics.activeChannels",
    helpId: "clusterMonitor.help.activeChannels",
    chartColor: "#0d9488",
    precision: 0,
    stage: "channelReplication",
    tone: "normal",
  },
  channelRuntimeLoadRate: {
    titleId: "clusterMonitor.metrics.channelRuntimeLoadRate",
    helpId: "clusterMonitor.help.channelRuntimeLoadRate",
    chartColor: "#0891b2",
    precision: 2,
    stage: "channelReplication",
    tone: "normal",
  },
  channelRuntimeIdleEvictionRate: {
    titleId: "clusterMonitor.metrics.channelRuntimeIdleEvictionRate",
    helpId: "clusterMonitor.help.channelRuntimeIdleEvictionRate",
    chartColor: "#65a30d",
    precision: 2,
    stage: "channelReplication",
    tone: "normal",
  },
  channelAppendBatchRecordsP95: {
    titleId: "clusterMonitor.metrics.channelAppendBatchRecordsP95",
    helpId: "clusterMonitor.help.channelAppendBatchRecordsP95",
    chartColor: "#2563eb",
    precision: 0,
    stage: "channelReplication",
    tone: "normal",
  },
  channelAppendBatchBytesP95: {
    titleId: "clusterMonitor.metrics.channelAppendBatchBytesP95",
    helpId: "clusterMonitor.help.channelAppendBatchBytesP95",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "channelReplication",
    tone: "normal",
  },
  channelAppendErrorRate: {
    titleId: "clusterMonitor.metrics.channelAppendErrorRate",
    helpId: "clusterMonitor.help.channelAppendErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "channelReplication",
    tone: "critical",
  },
  channelWriterAdmissionUsage: {
    titleId: "clusterMonitor.metrics.channelWriterAdmissionUsage",
    helpId: "clusterMonitor.help.channelWriterAdmissionUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelRuntimeFollowersParked: {
    titleId: "clusterMonitor.metrics.channelRuntimeFollowersParked",
    helpId: "clusterMonitor.help.channelRuntimeFollowersParked",
    chartColor: "#d97706",
    precision: 0,
    stage: "channelReplication",
    tone: "warning",
  },
  channelActivationRejectRate: {
    titleId: "clusterMonitor.metrics.channelActivationRejectRate",
    helpId: "clusterMonitor.help.channelActivationRejectRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "channelReplication",
    tone: "critical",
  },
  channelReactorMailboxDepth: {
    titleId: "clusterMonitor.metrics.channelReactorMailboxDepth",
    helpId: "clusterMonitor.help.channelReactorMailboxDepth",
    chartColor: "#ea580c",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelWorkerQueueDepth: {
    titleId: "clusterMonitor.metrics.channelWorkerQueueDepth",
    helpId: "clusterMonitor.help.channelWorkerQueueDepth",
    chartColor: "#f97316",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  channelPullHintErrorRate: {
    titleId: "clusterMonitor.metrics.channelPullHintErrorRate",
    helpId: "clusterMonitor.help.channelPullHintErrorRate",
    chartColor: "#be123c",
    precision: 2,
    stage: "channelReplication",
    tone: "critical",
  },
  channelReplicationLatencyP99: {
    titleId: "clusterMonitor.metrics.channelReplicationLatencyP99",
    helpId: "clusterMonitor.help.channelReplicationLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "channelReplication",
    tone: "warning",
  },
  internalTraffic: {
    titleId: "clusterMonitor.metrics.internalTraffic",
    helpId: "clusterMonitor.help.internalTraffic",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  internalTxTraffic: {
    titleId: "clusterMonitor.metrics.internalTxTraffic",
    helpId: "clusterMonitor.help.internalTxTraffic",
    chartColor: "#0891b2",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  internalRxTraffic: {
    titleId: "clusterMonitor.metrics.internalRxTraffic",
    helpId: "clusterMonitor.help.internalRxTraffic",
    chartColor: "#0d9488",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcRate: {
    titleId: "clusterMonitor.metrics.rpcRate",
    helpId: "clusterMonitor.help.rpcRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcSuccessRate: {
    titleId: "clusterMonitor.metrics.rpcSuccessRate",
    helpId: "clusterMonitor.help.rpcSuccessRate",
    chartColor: "#0284c7",
    precision: 2,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcErrorRate: {
    titleId: "clusterMonitor.metrics.rpcErrorRate",
    helpId: "clusterMonitor.help.rpcErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "internalNetwork",
    tone: "critical",
  },
  rpcInflight: {
    titleId: "clusterMonitor.metrics.rpcInflight",
    helpId: "clusterMonitor.help.rpcInflight",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "internalNetwork",
    tone: "warning",
  },
  rpcLatencyP95: {
    titleId: "clusterMonitor.metrics.rpcLatencyP95",
    helpId: "clusterMonitor.help.rpcLatencyP95",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  rpcLatencyP99: {
    titleId: "clusterMonitor.metrics.rpcLatencyP99",
    helpId: "clusterMonitor.help.rpcLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  dialSuccessRate: {
    titleId: "clusterMonitor.metrics.dialSuccessRate",
    helpId: "clusterMonitor.help.dialSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "internalNetwork",
    tone: "normal",
  },
  dialLatencyP95: {
    titleId: "clusterMonitor.metrics.dialLatencyP95",
    helpId: "clusterMonitor.help.dialLatencyP95",
    chartColor: "#d97706",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  internalTransportQueueUsage: {
    titleId: "clusterMonitor.metrics.internalTransportQueueUsage",
    helpId: "clusterMonitor.help.internalTransportQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  internalTransportAdmissionErrorRate: {
    titleId: "clusterMonitor.metrics.internalTransportAdmissionErrorRate",
    helpId: "clusterMonitor.help.internalTransportAdmissionErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "runtimePressure",
    tone: "critical",
  },
  workqueuePressure: {
    titleId: "clusterMonitor.metrics.workqueuePressure",
    helpId: "clusterMonitor.help.workqueuePressure",
    chartColor: "#d97706",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeCpuPercent: {
    titleId: "clusterMonitor.metrics.nodeCpuPercent",
    helpId: "clusterMonitor.help.nodeCpuPercent",
    chartColor: "#dc2626",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeMemoryRSS: {
    titleId: "clusterMonitor.metrics.nodeMemoryRSS",
    helpId: "clusterMonitor.help.nodeMemoryRSS",
    chartColor: "#0f766e",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGoroutines: {
    titleId: "clusterMonitor.metrics.nodeGoroutines",
    helpId: "clusterMonitor.help.nodeGoroutines",
    chartColor: "#475569",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  goroutineProcessHistory: {
    titleId: "clusterMonitor.metrics.goroutineProcessHistory",
    helpId: "clusterMonitor.help.goroutineProcessHistory",
    chartColor: "#475569",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  goroutineModuleHistory: {
    titleId: "clusterMonitor.metrics.goroutineModuleHistory",
    helpId: "clusterMonitor.help.goroutineModuleHistory",
    chartColor: "#2563eb",
    precision: 0,
    stage: "runtimePressure",
    tone: "normal",
  },
  nodeGCPauseRate: {
    titleId: "clusterMonitor.metrics.nodeGCPauseRate",
    helpId: "clusterMonitor.help.nodeGCPauseRate",
    chartColor: "#be123c",
    precision: 2,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGCRate: {
    titleId: "clusterMonitor.metrics.nodeGCRate",
    helpId: "clusterMonitor.help.nodeGCRate",
    chartColor: "#ca8a04",
    precision: 2,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGCCPUFraction: {
    titleId: "clusterMonitor.metrics.nodeGCCPUFraction",
    helpId: "clusterMonitor.help.nodeGCCPUFraction",
    chartColor: "#7c3aed",
    precision: 2,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGCHeapGoalUsage: {
    titleId: "clusterMonitor.metrics.nodeGCHeapGoalUsage",
    helpId: "clusterMonitor.help.nodeGCHeapGoalUsage",
    chartColor: "#0891b2",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageWriteP99: {
    titleId: "clusterMonitor.metrics.storageWriteP99",
    helpId: "clusterMonitor.help.storageWriteP99",
    chartColor: "#db2777",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageCommitErrorRate: {
    titleId: "clusterMonitor.metrics.storageCommitErrorRate",
    helpId: "clusterMonitor.help.storageCommitErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "incidentClosure",
    tone: "critical",
  },
  storageCommitQueueUsage: {
    titleId: "clusterMonitor.metrics.storageCommitQueueUsage",
    helpId: "clusterMonitor.help.storageCommitQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storagePhysicalCommitP99: {
    titleId: "clusterMonitor.metrics.storagePhysicalCommitP99",
    helpId: "clusterMonitor.help.storagePhysicalCommitP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageCommitBatchRecordsP95: {
    titleId: "clusterMonitor.metrics.storageCommitBatchRecordsP95",
    helpId: "clusterMonitor.help.storageCommitBatchRecordsP95",
    chartColor: "#2563eb",
    precision: 0,
    stage: "runtimePressure",
    tone: "normal",
  },
  storageCommitBatchBytesP95: {
    titleId: "clusterMonitor.metrics.storageCommitBatchBytesP95",
    helpId: "clusterMonitor.help.storageCommitBatchBytesP95",
    chartColor: "#0d9488",
    precision: 1,
    stage: "runtimePressure",
    tone: "normal",
  },
  storagePebbleDiskUsage: {
    titleId: "clusterMonitor.metrics.storagePebbleDiskUsage",
    helpId: "clusterMonitor.help.storagePebbleDiskUsage",
    chartColor: "#be185d",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storagePebbleReadAmplification: {
    titleId: "clusterMonitor.metrics.storagePebbleReadAmplification",
    helpId: "clusterMonitor.help.storagePebbleReadAmplification",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  storagePebbleCompactionDebt: {
    titleId: "clusterMonitor.metrics.storagePebbleCompactionDebt",
    helpId: "clusterMonitor.help.storagePebbleCompactionDebt",
    chartColor: "#7c2d12",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  sendRate: {
    titleId: "monitor.metrics.sendRate",
    helpId: "monitor.help.sendRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  sendSuccessRate: {
    titleId: "monitor.metrics.sendSuccessRate",
    helpId: "monitor.help.sendSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "sendEntry",
    tone: "normal",
  },
  entryLatencyP99: {
    titleId: "monitor.metrics.entryLatencyP99",
    helpId: "monitor.help.entryLatencyP99",
    chartColor: "#d97706",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  messageSendRate: {
    titleId: "monitor.metrics.messageSendRate",
    helpId: "monitor.help.messageSendRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  messageSendackErrorRate: {
    titleId: "monitor.metrics.messageSendackErrorRate",
    helpId: "monitor.help.messageSendackErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  sendQueueUsage: {
    titleId: "monitor.metrics.sendQueueUsage",
    helpId: "monitor.help.sendQueueUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  connectionOpenRate: {
    titleId: "monitor.metrics.connectionOpenRate",
    helpId: "monitor.help.connectionOpenRate",
    chartColor: "#0284c7",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  connectionCloseRate: {
    titleId: "monitor.metrics.connectionCloseRate",
    helpId: "monitor.help.connectionCloseRate",
    chartColor: "#ea580c",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  connectionCloseReasonRate: {
    titleId: "monitor.metrics.connectionCloseReasonRate",
    helpId: "monitor.help.connectionCloseReasonRate",
    chartColor: "#f97316",
    precision: 1,
    stage: "incidentClosure",
    tone: "warning",
  },
  authSuccessRate: {
    titleId: "monitor.metrics.authSuccessRate",
    helpId: "monitor.help.authSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "sendEntry",
    tone: "normal",
  },
  authLatencyP99: {
    titleId: "monitor.metrics.authLatencyP99",
    helpId: "monitor.help.authLatencyP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  sendackErrorRate: {
    titleId: "monitor.metrics.sendackErrorRate",
    helpId: "monitor.help.sendackErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "incidentClosure",
    tone: "critical",
  },
  gatewayInboundTraffic: {
    titleId: "monitor.metrics.gatewayInboundTraffic",
    helpId: "monitor.help.gatewayInboundTraffic",
    chartColor: "#0891b2",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  gatewayOutboundTraffic: {
    titleId: "monitor.metrics.gatewayOutboundTraffic",
    helpId: "monitor.help.gatewayOutboundTraffic",
    chartColor: "#0d9488",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  frameHandleLatencyP99: {
    titleId: "monitor.metrics.frameHandleLatencyP99",
    helpId: "monitor.help.frameHandleLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  asyncBatchWaitP99: {
    titleId: "monitor.metrics.asyncBatchWaitP99",
    helpId: "monitor.help.asyncBatchWaitP99",
    chartColor: "#d97706",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  asyncBatchRecordsP95: {
    titleId: "monitor.metrics.asyncBatchRecordsP95",
    helpId: "monitor.help.asyncBatchRecordsP95",
    chartColor: "#2563eb",
    precision: 0,
    stage: "sendEntry",
    tone: "normal",
  },
  asyncBatchBytesP95: {
    titleId: "monitor.metrics.asyncBatchBytesP95",
    helpId: "monitor.help.asyncBatchBytesP95",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  authQueueUsage: {
    titleId: "monitor.metrics.authQueueUsage",
    helpId: "monitor.help.authQueueUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  transportQueueUsage: {
    titleId: "monitor.metrics.transportQueueUsage",
    helpId: "monitor.help.transportQueueUsage",
    chartColor: "#ea580c",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  transportBytesUsage: {
    titleId: "monitor.metrics.transportBytesUsage",
    helpId: "monitor.help.transportBytesUsage",
    chartColor: "#dc2626",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  commitRate: {
    titleId: "monitor.metrics.commitRate",
    helpId: "monitor.help.commitRate",
    chartColor: "#0f766e",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  messageAppendErrorRate: {
    titleId: "monitor.metrics.messageAppendErrorRate",
    helpId: "monitor.help.messageAppendErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "appendCommit",
    tone: "critical",
  },
  messageAppendLatencyP95: {
    titleId: "monitor.metrics.messageAppendLatencyP95",
    helpId: "monitor.help.messageAppendLatencyP95",
    chartColor: "#9333ea",
    precision: 1,
    stage: "appendCommit",
    tone: "warning",
  },
  commitLatencyP99: {
    titleId: "monitor.metrics.commitLatencyP99",
    helpId: "monitor.help.commitLatencyP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  pendingCommitBacklog: {
    titleId: "monitor.metrics.pendingCommitBacklog",
    helpId: "monitor.help.pendingCommitBacklog",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "appendCommit",
    tone: "warning",
  },
  messageDispatchEnqueueRate: {
    titleId: "monitor.metrics.messageDispatchEnqueueRate",
    helpId: "monitor.help.messageDispatchEnqueueRate",
    chartColor: "#0d9488",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  messageDispatchOverflowRate: {
    titleId: "monitor.metrics.messageDispatchOverflowRate",
    helpId: "monitor.help.messageDispatchOverflowRate",
    chartColor: "#f97316",
    precision: 2,
    stage: "appendCommit",
    tone: "critical",
  },
  conversationDirectoryRate: {
    titleId: "monitor.metrics.conversationDirectoryRate",
    helpId: "monitor.help.conversationDirectoryRate",
    chartColor: "#0284c7",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationDirectoryLatencyP99: {
    titleId: "monitor.metrics.conversationDirectoryLatencyP99",
    helpId: "monitor.help.conversationDirectoryLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationDirectoryErrorRate: {
    titleId: "monitor.metrics.conversationDirectoryErrorRate",
    helpId: "monitor.help.conversationDirectoryErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "conversationSync",
    tone: "critical",
  },
  conversationScannedCandidates: {
    titleId: "monitor.metrics.conversationScannedCandidates",
    helpId: "monitor.help.conversationScannedCandidates",
    chartColor: "#0891b2",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationReturnedItems: {
    titleId: "monitor.metrics.conversationReturnedItems",
    helpId: "monitor.help.conversationReturnedItems",
    chartColor: "#059669",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationDeletes: {
    titleId: "monitor.metrics.conversationDeletes",
    helpId: "monitor.help.conversationDeletes",
    chartColor: "#64748b",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationUnresolved: {
    titleId: "monitor.metrics.conversationUnresolved",
    helpId: "monitor.help.conversationUnresolved",
    chartColor: "#f97316",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationHydrationLatencyP99: {
    titleId: "monitor.metrics.conversationHydrationLatencyP99",
    helpId: "monitor.help.conversationHydrationLatencyP99",
    chartColor: "#c026d3",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationHydrationRemoteBatches: {
    titleId: "monitor.metrics.conversationHydrationRemoteBatches",
    helpId: "monitor.help.conversationHydrationRemoteBatches",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationHydrationLocalReads: {
    titleId: "monitor.metrics.conversationHydrationLocalReads",
    helpId: "monitor.help.conversationHydrationLocalReads",
    chartColor: "#d97706",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  deliveryRate: {
    titleId: "monitor.metrics.deliveryRate",
    helpId: "monitor.help.deliveryRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryLatencyP99: {
    titleId: "monitor.metrics.deliveryLatencyP99",
    helpId: "monitor.help.deliveryLatencyP99",
    chartColor: "#db2777",
    precision: 1,
    stage: "onlineDelivery",
    tone: "warning",
  },
  fanOutRatio: {
    titleId: "monitor.metrics.fanOutRatio",
    helpId: "monitor.help.fanOutRatio",
    chartColor: "#4f46e5",
    precision: 2,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryEnqueueRate: {
    titleId: "monitor.metrics.deliveryEnqueueRate",
    helpId: "monitor.help.deliveryEnqueueRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryQueueUsage: {
    titleId: "monitor.metrics.deliveryQueueUsage",
    helpId: "monitor.help.deliveryQueueUsage",
    chartColor: "#ca8a04",
    precision: 1,
    stage: "onlineDelivery",
    tone: "warning",
  },
  deliveryRetryRate: {
    titleId: "monitor.metrics.deliveryRetryRate",
    helpId: "monitor.help.deliveryRetryRate",
    chartColor: "#d97706",
    precision: 2,
    stage: "offlineRetry",
    tone: "warning",
  },
  deliveryAdmissionErrorRate: {
    titleId: "monitor.metrics.deliveryAdmissionErrorRate",
    helpId: "monitor.help.deliveryAdmissionErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "onlineDelivery",
    tone: "critical",
  },
  deliveryRouteExpireRate: {
    titleId: "monitor.metrics.deliveryRouteExpireRate",
    helpId: "monitor.help.deliveryRouteExpireRate",
    chartColor: "#be123c",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  offlineEnqueueRate: {
    titleId: "monitor.metrics.offlineEnqueueRate",
    helpId: "monitor.help.offlineEnqueueRate",
    chartColor: "#64748b",
    precision: 1,
    stage: "offlineRetry",
    tone: "normal",
  },
  retryQueueDepth: {
    titleId: "monitor.metrics.retryQueueDepth",
    helpId: "monitor.help.retryQueueDepth",
    chartColor: "#ea580c",
    precision: 0,
    stage: "offlineRetry",
    tone: "warning",
  },
  pathErrorRate: {
    titleId: "monitor.metrics.pathErrorRate",
    helpId: "monitor.help.pathErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  activeConnections: {
    titleId: "monitor.metrics.onlineConnections",
    helpId: "monitor.help.onlineConnections",
    chartColor: "#0d9488",
    precision: 0,
    stage: "sendEntry",
    tone: "normal",
  },
}

export const clusterMonitorStageLabelIds: Record<ClusterMonitorStage, string> = {
  controlPlane: "clusterMonitor.stage.controlPlane",
  slotReplication: "clusterMonitor.stage.slotReplication",
  channelReplication: "clusterMonitor.stage.channelReplication",
  internalNetwork: "clusterMonitor.stage.internalNetwork",
  runtimePressure: "clusterMonitor.stage.runtimePressure",
  incidentClosure: "clusterMonitor.stage.incidentClosure",
  sendEntry: "monitor.stage.sendEntry",
  appendCommit: "monitor.stage.appendCommit",
  conversationSync: "monitor.stage.conversationSync",
  onlineDelivery: "monitor.stage.onlineDelivery",
  offlineRetry: "monitor.stage.offlineRetry",
  errorClosure: "monitor.stage.errorClosure",
}

export const clusterMonitorStatusByTone: Record<ClusterMonitorTone, string> = {
  normal: "clusterMonitor.status.normal",
  warning: "clusterMonitor.status.warning",
  critical: "clusterMonitor.status.critical",
  preview: "clusterMonitor.status.preview",
}

export const clusterMonitorSnapshotLabelIds: Record<string, string> = {
  goroutineProcessTotal: "clusterMonitor.goroutines.processTotal",
  goroutineManagedTotal: "clusterMonitor.goroutines.managedTotal",
  goroutineUnmanagedTotal: "clusterMonitor.goroutines.unmanagedTotal",
  goroutinePanicTotal: "clusterMonitor.goroutines.panicTotal",
  goroutineSaturatedPools: "clusterMonitor.goroutines.saturatedPools",
  nodesAlive: "clusterMonitor.snapshot.nodesAlive",
  slotsReady: "clusterMonitor.snapshot.slotsReady",
  controllerApplyGap: "clusterMonitor.snapshot.controllerApplyGap",
  rpcErrorRate: "clusterMonitor.snapshot.rpcErrorRate",
  queuePressure: "clusterMonitor.snapshot.queuePressure",
  storageWriteP99: "clusterMonitor.snapshot.storageWriteP99",
  send: "monitor.snapshot.send",
  delivery: "monitor.snapshot.delivery",
  entryP99: "monitor.snapshot.entryP99",
  conversationDirectoryP99: "monitor.snapshot.conversationDirectoryP99",
  conversationDirectoryErrors: "monitor.snapshot.conversationDirectoryErrors",
  conversationUnresolved: "monitor.snapshot.conversationUnresolved",
  conversationHydrationP99: "monitor.snapshot.conversationHydrationP99",
  deliveryP99: "monitor.snapshot.deliveryP99",
  errors: "monitor.snapshot.errors",
  retryDepth: "monitor.snapshot.retryDepth",
  online: "monitor.snapshot.online",
}

export const clusterMonitorStatLabelIds: Record<string, string> = {
  avg: "clusterMonitor.stat.avg",
  min: "clusterMonitor.stat.min",
  peak: "clusterMonitor.stat.peak",
  total: "monitor.stat.total",
  latest: "clusterMonitor.stat.latest",
  rejected: "clusterMonitor.stat.rejected",
  p95Gap: "clusterMonitor.stat.p95Gap",
  maxGap: "clusterMonitor.stat.maxGap",
  slowNodes: "clusterMonitor.stat.slowNodes",
  leaderMissing: "clusterMonitor.stat.leaderMissing",
  quorumLost: "clusterMonitor.stat.quorumLost",
  transfers: "clusterMonitor.stat.transfers",
  p50: "clusterMonitor.stat.p50",
  p95: "clusterMonitor.stat.p95",
  laggingSlots: "clusterMonitor.stat.laggingSlots",
  isrInsufficient: "clusterMonitor.stat.isrInsufficient",
  noLeader: "clusterMonitor.stat.noLeader",
  affectedChannels: "clusterMonitor.stat.affectedChannels",
  slowAppends: "clusterMonitor.stat.slowAppends",
  tx: "clusterMonitor.stat.tx",
  rx: "clusterMonitor.stat.rx",
  callsPerSecond: "clusterMonitor.stat.callsPerSecond",
  errorsPerSecond: "clusterMonitor.stat.errorsPerSecond",
  timeouts: "clusterMonitor.stat.timeouts",
  inflight: "clusterMonitor.stat.inflight",
  busy: "clusterMonitor.stat.busy",
  critical: "clusterMonitor.stat.critical",
  queueFull: "clusterMonitor.stat.queueFull",
  flushWait: "clusterMonitor.stat.flushWait",
  warning: "clusterMonitor.stat.warning",
  topReason: "clusterMonitor.stat.topReason",
  unavailableReason: "clusterMonitor.stat.unavailableReason",
}
