import type { ClusterMonitorMetricKey, ClusterMonitorStage, ClusterMonitorTone } from "./types"

type ClusterMonitorMetricConfig = {
  titleId: string
  helpId: string
  chartColor: string
  precision: number
  stage: ClusterMonitorStage
  tone: ClusterMonitorTone
}

export const clusterMonitorMetricConfig: Record<ClusterMonitorMetricKey, ClusterMonitorMetricConfig> = {
  controllerProposeRate: {
    titleId: "clusterMonitor.metrics.controllerProposeRate",
    helpId: "clusterMonitor.help.controllerProposeRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "controlPlane",
    tone: "normal",
  },
  controllerApplyGap: {
    titleId: "clusterMonitor.metrics.controllerApplyGap",
    helpId: "clusterMonitor.help.controllerApplyGap",
    chartColor: "#1d4ed8",
    precision: 0,
    stage: "controlPlane",
    tone: "warning",
  },
  slotLeaderStability: {
    titleId: "clusterMonitor.metrics.slotLeaderStability",
    helpId: "clusterMonitor.help.slotLeaderStability",
    chartColor: "#0f766e",
    precision: 2,
    stage: "slotReplication",
    tone: "normal",
  },
  slotProposeRate: {
    titleId: "clusterMonitor.metrics.slotProposeRate",
    helpId: "clusterMonitor.help.slotProposeRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "slotReplication",
    tone: "normal",
  },
  slotApplyGap: {
    titleId: "clusterMonitor.metrics.slotApplyGap",
    helpId: "clusterMonitor.help.slotApplyGap",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "slotReplication",
    tone: "warning",
  },
  slotLatencyP99: {
    titleId: "clusterMonitor.metrics.slotLatencyP99",
    helpId: "clusterMonitor.help.slotLatencyP99",
    chartColor: "#16a34a",
    precision: 1,
    stage: "slotReplication",
    tone: "warning",
  },
  channelAppendLatencyP99: {
    titleId: "clusterMonitor.metrics.channelAppendLatencyP99",
    helpId: "clusterMonitor.help.channelAppendLatencyP99",
    chartColor: "#22c55e",
    precision: 1,
    stage: "channelReplication",
    tone: "normal",
  },
  activeChannels: {
    titleId: "clusterMonitor.metrics.activeChannels",
    helpId: "clusterMonitor.help.activeChannels",
    chartColor: "#0d9488",
    precision: 0,
    stage: "channelReplication",
    tone: "normal",
  },
  internalTraffic: {
    titleId: "clusterMonitor.metrics.internalTraffic",
    helpId: "clusterMonitor.help.internalTraffic",
    chartColor: "#4f46e5",
    precision: 1,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcSuccessRate: {
    titleId: "clusterMonitor.metrics.rpcSuccessRate",
    helpId: "clusterMonitor.help.rpcSuccessRate",
    chartColor: "#0284c7",
    precision: 2,
    stage: "internalNetwork",
    tone: "normal",
  },
  rpcLatencyP95: {
    titleId: "clusterMonitor.metrics.rpcLatencyP95",
    helpId: "clusterMonitor.help.rpcLatencyP95",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "internalNetwork",
    tone: "warning",
  },
  workqueuePressure: {
    titleId: "clusterMonitor.metrics.workqueuePressure",
    helpId: "clusterMonitor.help.workqueuePressure",
    chartColor: "#d97706",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeCpuPercent: {
    titleId: "clusterMonitor.metrics.nodeCpuPercent",
    helpId: "clusterMonitor.help.nodeCpuPercent",
    chartColor: "#dc2626",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeMemoryRSS: {
    titleId: "clusterMonitor.metrics.nodeMemoryRSS",
    helpId: "clusterMonitor.help.nodeMemoryRSS",
    chartColor: "#0f766e",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  nodeGoroutines: {
    titleId: "clusterMonitor.metrics.nodeGoroutines",
    helpId: "clusterMonitor.help.nodeGoroutines",
    chartColor: "#475569",
    precision: 0,
    stage: "runtimePressure",
    tone: "warning",
  },
  storageWriteP99: {
    titleId: "clusterMonitor.metrics.storageWriteP99",
    helpId: "clusterMonitor.help.storageWriteP99",
    chartColor: "#db2777",
    precision: 1,
    stage: "runtimePressure",
    tone: "warning",
  },
  sendRate: {
    titleId: "monitor.metrics.sendRate",
    helpId: "monitor.help.sendRate",
    chartColor: "#2563eb",
    precision: 1,
    stage: "sendEntry",
    tone: "normal",
  },
  sendSuccessRate: {
    titleId: "monitor.metrics.sendSuccessRate",
    helpId: "monitor.help.sendSuccessRate",
    chartColor: "#16a34a",
    precision: 2,
    stage: "sendEntry",
    tone: "normal",
  },
  entryLatencyP99: {
    titleId: "monitor.metrics.entryLatencyP99",
    helpId: "monitor.help.entryLatencyP99",
    chartColor: "#d97706",
    precision: 1,
    stage: "sendEntry",
    tone: "warning",
  },
  commitRate: {
    titleId: "monitor.metrics.commitRate",
    helpId: "monitor.help.commitRate",
    chartColor: "#0f766e",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  commitLatencyP99: {
    titleId: "monitor.metrics.commitLatencyP99",
    helpId: "monitor.help.commitLatencyP99",
    chartColor: "#7c3aed",
    precision: 1,
    stage: "appendCommit",
    tone: "normal",
  },
  pendingCommitBacklog: {
    titleId: "monitor.metrics.pendingCommitBacklog",
    helpId: "monitor.help.pendingCommitBacklog",
    chartColor: "#ca8a04",
    precision: 0,
    stage: "appendCommit",
    tone: "warning",
  },
  conversationSyncRate: {
    titleId: "monitor.metrics.conversationSyncRate",
    helpId: "monitor.help.conversationSyncRate",
    chartColor: "#0284c7",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationSyncLatencyP99: {
    titleId: "monitor.metrics.conversationSyncLatencyP99",
    helpId: "monitor.help.conversationSyncLatencyP99",
    chartColor: "#9333ea",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationSyncErrorRate: {
    titleId: "monitor.metrics.conversationSyncErrorRate",
    helpId: "monitor.help.conversationSyncErrorRate",
    chartColor: "#e11d48",
    precision: 2,
    stage: "conversationSync",
    tone: "critical",
  },
  conversationReturnedItems: {
    titleId: "monitor.metrics.conversationReturnedItems",
    helpId: "monitor.help.conversationReturnedItems",
    chartColor: "#059669",
    precision: 1,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationRecentLoadLatencyP99: {
    titleId: "monitor.metrics.conversationRecentLoadLatencyP99",
    helpId: "monitor.help.conversationRecentLoadLatencyP99",
    chartColor: "#c026d3",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveDirtyRows: {
    titleId: "monitor.metrics.conversationActiveDirtyRows",
    helpId: "monitor.help.conversationActiveDirtyRows",
    chartColor: "#f59e0b",
    precision: 0,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveNormalRows: {
    titleId: "monitor.metrics.conversationActiveNormalRows",
    helpId: "monitor.help.conversationActiveNormalRows",
    chartColor: "#0f766e",
    precision: 0,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationActiveCMDRows: {
    titleId: "monitor.metrics.conversationActiveCMDRows",
    helpId: "monitor.help.conversationActiveCMDRows",
    chartColor: "#0891b2",
    precision: 0,
    stage: "conversationSync",
    tone: "normal",
  },
  conversationActiveNormalDirtyRows: {
    titleId: "monitor.metrics.conversationActiveNormalDirtyRows",
    helpId: "monitor.help.conversationActiveNormalDirtyRows",
    chartColor: "#f97316",
    precision: 0,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveCMDDirtyRows: {
    titleId: "monitor.metrics.conversationActiveCMDDirtyRows",
    helpId: "monitor.help.conversationActiveCMDDirtyRows",
    chartColor: "#ea580c",
    precision: 0,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveOldestDirtyAge: {
    titleId: "monitor.metrics.conversationActiveOldestDirtyAge",
    helpId: "monitor.help.conversationActiveOldestDirtyAge",
    chartColor: "#d97706",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveFlushLatencyP99: {
    titleId: "monitor.metrics.conversationActiveFlushLatencyP99",
    helpId: "monitor.help.conversationActiveFlushLatencyP99",
    chartColor: "#0d9488",
    precision: 1,
    stage: "conversationSync",
    tone: "warning",
  },
  conversationActiveFlushErrorRate: {
    titleId: "monitor.metrics.conversationActiveFlushErrorRate",
    helpId: "monitor.help.conversationActiveFlushErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "conversationSync",
    tone: "critical",
  },
  conversationAuthorityPressureRate: {
    titleId: "monitor.metrics.conversationAuthorityPressureRate",
    helpId: "monitor.help.conversationAuthorityPressureRate",
    chartColor: "#4f46e5",
    precision: 2,
    stage: "conversationSync",
    tone: "warning",
  },
  deliveryRate: {
    titleId: "monitor.metrics.deliveryRate",
    helpId: "monitor.help.deliveryRate",
    chartColor: "#0891b2",
    precision: 1,
    stage: "onlineDelivery",
    tone: "normal",
  },
  deliveryLatencyP99: {
    titleId: "monitor.metrics.deliveryLatencyP99",
    helpId: "monitor.help.deliveryLatencyP99",
    chartColor: "#db2777",
    precision: 1,
    stage: "onlineDelivery",
    tone: "warning",
  },
  fanOutRatio: {
    titleId: "monitor.metrics.fanOutRatio",
    helpId: "monitor.help.fanOutRatio",
    chartColor: "#4f46e5",
    precision: 2,
    stage: "onlineDelivery",
    tone: "normal",
  },
  offlineEnqueueRate: {
    titleId: "monitor.metrics.offlineEnqueueRate",
    helpId: "monitor.help.offlineEnqueueRate",
    chartColor: "#64748b",
    precision: 1,
    stage: "offlineRetry",
    tone: "normal",
  },
  retryQueueDepth: {
    titleId: "monitor.metrics.retryQueueDepth",
    helpId: "monitor.help.retryQueueDepth",
    chartColor: "#ea580c",
    precision: 0,
    stage: "offlineRetry",
    tone: "warning",
  },
  pathErrorRate: {
    titleId: "monitor.metrics.pathErrorRate",
    helpId: "monitor.help.pathErrorRate",
    chartColor: "#dc2626",
    precision: 2,
    stage: "errorClosure",
    tone: "critical",
  },
  activeConnections: {
    titleId: "monitor.metrics.onlineConnections",
    helpId: "monitor.help.onlineConnections",
    chartColor: "#0d9488",
    precision: 0,
    stage: "sendEntry",
    tone: "normal",
  },
}

export const clusterMonitorStageLabelIds: Record<ClusterMonitorStage, string> = {
  controlPlane: "clusterMonitor.stage.controlPlane",
  slotReplication: "clusterMonitor.stage.slotReplication",
  channelReplication: "clusterMonitor.stage.channelReplication",
  internalNetwork: "clusterMonitor.stage.internalNetwork",
  runtimePressure: "clusterMonitor.stage.runtimePressure",
  incidentClosure: "clusterMonitor.stage.incidentClosure",
  sendEntry: "monitor.stage.sendEntry",
  appendCommit: "monitor.stage.appendCommit",
  conversationSync: "monitor.stage.conversationSync",
  onlineDelivery: "monitor.stage.onlineDelivery",
  offlineRetry: "monitor.stage.offlineRetry",
  errorClosure: "monitor.stage.errorClosure",
}

export const clusterMonitorStatusByTone: Record<ClusterMonitorTone, string> = {
  normal: "clusterMonitor.status.normal",
  warning: "clusterMonitor.status.warning",
  critical: "clusterMonitor.status.critical",
  preview: "clusterMonitor.status.preview",
}

export const clusterMonitorSnapshotLabelIds: Record<string, string> = {
  nodesAlive: "clusterMonitor.snapshot.nodesAlive",
  slotsReady: "clusterMonitor.snapshot.slotsReady",
  controllerApplyGap: "clusterMonitor.snapshot.controllerApplyGap",
  rpcErrorRate: "clusterMonitor.snapshot.rpcErrorRate",
  queuePressure: "clusterMonitor.snapshot.queuePressure",
  storageWriteP99: "clusterMonitor.snapshot.storageWriteP99",
  send: "monitor.snapshot.send",
  delivery: "monitor.snapshot.delivery",
  entryP99: "monitor.snapshot.entryP99",
  conversationSyncP99: "monitor.snapshot.conversationSyncP99",
  conversationSyncErrors: "monitor.snapshot.conversationSyncErrors",
  conversationDirtyAge: "monitor.snapshot.conversationDirtyAge",
  conversationFlushErrors: "monitor.snapshot.conversationFlushErrors",
  deliveryP99: "monitor.snapshot.deliveryP99",
  errors: "monitor.snapshot.errors",
  retryDepth: "monitor.snapshot.retryDepth",
  online: "monitor.snapshot.online",
}

export const clusterMonitorStatLabelIds: Record<string, string> = {
  avg: "clusterMonitor.stat.avg",
  peak: "clusterMonitor.stat.peak",
  total: "monitor.stat.total",
  latest: "clusterMonitor.stat.latest",
  rejected: "clusterMonitor.stat.rejected",
  p95Gap: "clusterMonitor.stat.p95Gap",
  maxGap: "clusterMonitor.stat.maxGap",
  slowNodes: "clusterMonitor.stat.slowNodes",
  leaderMissing: "clusterMonitor.stat.leaderMissing",
  quorumLost: "clusterMonitor.stat.quorumLost",
  transfers: "clusterMonitor.stat.transfers",
  p50: "clusterMonitor.stat.p50",
  p95: "clusterMonitor.stat.p95",
  laggingSlots: "clusterMonitor.stat.laggingSlots",
  isrInsufficient: "clusterMonitor.stat.isrInsufficient",
  noLeader: "clusterMonitor.stat.noLeader",
  affectedChannels: "clusterMonitor.stat.affectedChannels",
  slowAppends: "clusterMonitor.stat.slowAppends",
  tx: "clusterMonitor.stat.tx",
  rx: "clusterMonitor.stat.rx",
  callsPerSecond: "clusterMonitor.stat.callsPerSecond",
  errorsPerSecond: "clusterMonitor.stat.errorsPerSecond",
  timeouts: "clusterMonitor.stat.timeouts",
  inflight: "clusterMonitor.stat.inflight",
  busy: "clusterMonitor.stat.busy",
  critical: "clusterMonitor.stat.critical",
  queueFull: "clusterMonitor.stat.queueFull",
  flushWait: "clusterMonitor.stat.flushWait",
  warning: "clusterMonitor.stat.warning",
  topReason: "clusterMonitor.stat.topReason",
  unavailableReason: "clusterMonitor.stat.unavailableReason",
}
