// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: internal/pb/cluster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_Unknown      Role = 0
	Role_Follower     Role = 1
	Role_Candidate    Role = 2
	Role_PreCandidate Role = 3
	Role_Leader       Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "Unknown",
		1: "Follower",
		2: "Candidate",
		3: "PreCandidate",
		4: "Leader",
	}
	Role_value = map[string]int32{
		"Unknown":      0,
		"Follower":     1,
		"Candidate":    2,
		"PreCandidate": 3,
		"Leader":       4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_cluster_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_internal_pb_cluster_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{0}
}

type SlotState int32

const (
	SlotState_SlotWait      SlotState = 0 // slots等待分配
	SlotState_SlotReady     SlotState = 1 // slots已准备就绪
	SlotState_SlotMigration SlotState = 2 // slots需要迁移
)

// Enum value maps for SlotState.
var (
	SlotState_name = map[int32]string{
		0: "SlotWait",
		1: "SlotReady",
		2: "SlotMigration",
	}
	SlotState_value = map[string]int32{
		"SlotWait":      0,
		"SlotReady":     1,
		"SlotMigration": 2,
	}
)

func (x SlotState) Enum() *SlotState {
	p := new(SlotState)
	*p = x
	return p
}

func (x SlotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_cluster_proto_enumTypes[1].Descriptor()
}

func (SlotState) Type() protoreflect.EnumType {
	return &file_internal_pb_cluster_proto_enumTypes[1]
}

func (x SlotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotState.Descriptor instead.
func (SlotState) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{1}
}

type NodeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID   uint32 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`       // 节点ID
	NodeAddr string `protobuf:"bytes,2,opt,name=nodeAddr,proto3" json:"nodeAddr,omitempty"`    // 节点地址
	Role     Role   `protobuf:"varint,3,opt,name=role,proto3,enum=Role" json:"role,omitempty"` // 节点角色
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetNodeID() uint32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *NodeConfig) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

func (x *NodeConfig) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_Unknown
}

type GatewayConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID  uint32 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`  // 节点ID
	TcpAddr string `protobuf:"bytes,2,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"` // 节点tcp对外地址
	WsAddr  string `protobuf:"bytes,3,opt,name=wsAddr,proto3" json:"wsAddr,omitempty"`   // 节点websocket对外地址
	WssAddr string `protobuf:"bytes,4,opt,name=wssAddr,proto3" json:"wssAddr,omitempty"` // 节点 wss对外地址
}

func (x *GatewayConfig) Reset() {
	*x = GatewayConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfig) ProtoMessage() {}

func (x *GatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfig.ProtoReflect.Descriptor instead.
func (*GatewayConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayConfig) GetNodeID() uint32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *GatewayConfig) GetTcpAddr() string {
	if x != nil {
		return x.TcpAddr
	}
	return ""
}

func (x *GatewayConfig) GetWsAddr() string {
	if x != nil {
		return x.WsAddr
	}
	return ""
}

func (x *GatewayConfig) GetWssAddr() string {
	if x != nil {
		return x.WssAddr
	}
	return ""
}

type ClusterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterID          uint32        `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`             // cluster id
	LeaderID           uint32        `protobuf:"varint,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`               // 领导节点的id
	Version            uint32        `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                 // 配置版本
	Replica            uint32        `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`                 // 副本数
	SlotCount          uint32        `protobuf:"varint,5,opt,name=slotCount,proto3" json:"slotCount,omitempty"`             // slot 总数量
	Slots              []byte        `protobuf:"bytes,6,opt,name=slots,proto3" json:"slots,omitempty"`                      // slot bitmap
	ImportClusterID    int32         `protobuf:"varint,7,opt,name=importClusterID,proto3" json:"importClusterID,omitempty"` // 要导入的集群ID
	ImportWill         []byte        `protobuf:"bytes,8,opt,name=importWill,proto3" json:"importWill,omitempty"`            // 将要引入的slots
	ExportWill         []byte        `protobuf:"bytes,9,opt,name=exportWill,proto3" json:"exportWill,omitempty"`            // 将要导出的slots
	Exporting          []byte        `protobuf:"bytes,10,opt,name=exporting,proto3" json:"exporting,omitempty"`             // 正在导出的slot（正在导出的slot将被锁定，不接受数据）
	ExportedList       *ExportedList `protobuf:"bytes,11,opt,name=exportedList,proto3" json:"exportedList,omitempty"`       // 已导出的slot
	SlotState          SlotState     `protobuf:"varint,15,opt,name=slotState,proto3,enum=SlotState" json:"slotState,omitempty"`
	StartExport        bool          `protobuf:"varint,16,opt,name=startExport,proto3" json:"startExport,omitempty"`                      // 是否开始导出
	ImportedNodeIDList []int32       `protobuf:"varint,17,rep,packed,name=importedNodeIDList,proto3" json:"importedNodeIDList,omitempty"` // 已导入节点列表
	Nodes              []*NodeConfig `protobuf:"bytes,18,rep,name=nodes,proto3" json:"nodes,omitempty"`                                   // 节点信息
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterConfig) GetClusterID() uint32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

func (x *ClusterConfig) GetLeaderID() uint32 {
	if x != nil {
		return x.LeaderID
	}
	return 0
}

func (x *ClusterConfig) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterConfig) GetReplica() uint32 {
	if x != nil {
		return x.Replica
	}
	return 0
}

func (x *ClusterConfig) GetSlotCount() uint32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *ClusterConfig) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ClusterConfig) GetImportClusterID() int32 {
	if x != nil {
		return x.ImportClusterID
	}
	return 0
}

func (x *ClusterConfig) GetImportWill() []byte {
	if x != nil {
		return x.ImportWill
	}
	return nil
}

func (x *ClusterConfig) GetExportWill() []byte {
	if x != nil {
		return x.ExportWill
	}
	return nil
}

func (x *ClusterConfig) GetExporting() []byte {
	if x != nil {
		return x.Exporting
	}
	return nil
}

func (x *ClusterConfig) GetExportedList() *ExportedList {
	if x != nil {
		return x.ExportedList
	}
	return nil
}

func (x *ClusterConfig) GetSlotState() SlotState {
	if x != nil {
		return x.SlotState
	}
	return SlotState_SlotWait
}

func (x *ClusterConfig) GetStartExport() bool {
	if x != nil {
		return x.StartExport
	}
	return false
}

func (x *ClusterConfig) GetImportedNodeIDList() []int32 {
	if x != nil {
		return x.ImportedNodeIDList
	}
	return nil
}

func (x *ClusterConfig) GetNodes() []*NodeConfig {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ClusterConfigSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clusters []*ClusterConfig `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Gateways []*GatewayConfig `protobuf:"bytes,2,rep,name=gateways,proto3" json:"gateways,omitempty"`
}

func (x *ClusterConfigSet) Reset() {
	*x = ClusterConfigSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfigSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigSet) ProtoMessage() {}

func (x *ClusterConfigSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigSet.ProtoReflect.Descriptor instead.
func (*ClusterConfigSet) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterConfigSet) GetClusters() []*ClusterConfig {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClusterConfigSet) GetGateways() []*GatewayConfig {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type ExportedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exported []*Exported `protobuf:"bytes,1,rep,name=exported,proto3" json:"exported,omitempty"`
}

func (x *ExportedList) Reset() {
	*x = ExportedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportedList) ProtoMessage() {}

func (x *ExportedList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportedList.ProtoReflect.Descriptor instead.
func (*ExportedList) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ExportedList) GetExported() []*Exported {
	if x != nil {
		return x.Exported
	}
	return nil
}

type Exported struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No    string `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Slots []byte `protobuf:"bytes,2,opt,name=slots,proto3" json:"slots,omitempty"` // 已导出的slots
	Path  string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`   // 对应的备份路径
}

func (x *Exported) Reset() {
	*x = Exported{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exported) ProtoMessage() {}

func (x *Exported) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exported.ProtoReflect.Descriptor instead.
func (*Exported) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *Exported) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *Exported) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *Exported) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_internal_pb_cluster_proto protoreflect.FileDescriptor

var file_internal_pb_cluster_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0a, 0x4e,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x19, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x73, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x73, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x73, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x22, 0x8b, 0x04,
	0x0a, 0x0d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x31, 0x0a, 0x0c, 0x65, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0c,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09,
	0x73, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0a, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x73, 0x6c, 0x6f,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x11,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x12, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x74, 0x12,
	0x2a, 0x0a, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x08, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x22, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x22, 0x44,
	0x0a, 0x08, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x2a, 0x4e, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x10, 0x04, 0x2a, 0x3b, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x6c, 0x6f, 0x74, 0x57, 0x61, 0x69, 0x74, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x6c, 0x6f, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10,
	0x02, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_pb_cluster_proto_rawDescOnce sync.Once
	file_internal_pb_cluster_proto_rawDescData = file_internal_pb_cluster_proto_rawDesc
)

func file_internal_pb_cluster_proto_rawDescGZIP() []byte {
	file_internal_pb_cluster_proto_rawDescOnce.Do(func() {
		file_internal_pb_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_cluster_proto_rawDescData)
	})
	return file_internal_pb_cluster_proto_rawDescData
}

var file_internal_pb_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_pb_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pb_cluster_proto_goTypes = []interface{}{
	(Role)(0),                // 0: Role
	(SlotState)(0),           // 1: SlotState
	(*NodeConfig)(nil),       // 2: NodeConfig
	(*GatewayConfig)(nil),    // 3: GatewayConfig
	(*ClusterConfig)(nil),    // 4: ClusterConfig
	(*ClusterConfigSet)(nil), // 5: ClusterConfigSet
	(*ExportedList)(nil),     // 6: ExportedList
	(*Exported)(nil),         // 7: Exported
}
var file_internal_pb_cluster_proto_depIdxs = []int32{
	0, // 0: NodeConfig.role:type_name -> Role
	6, // 1: ClusterConfig.exportedList:type_name -> ExportedList
	1, // 2: ClusterConfig.slotState:type_name -> SlotState
	2, // 3: ClusterConfig.nodes:type_name -> NodeConfig
	4, // 4: ClusterConfigSet.clusters:type_name -> ClusterConfig
	3, // 5: ClusterConfigSet.gateways:type_name -> GatewayConfig
	7, // 6: ExportedList.exported:type_name -> Exported
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_pb_cluster_proto_init() }
func file_internal_pb_cluster_proto_init() {
	if File_internal_pb_cluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_cluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfigSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exported); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_cluster_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_cluster_proto_goTypes,
		DependencyIndexes: file_internal_pb_cluster_proto_depIdxs,
		EnumInfos:         file_internal_pb_cluster_proto_enumTypes,
		MessageInfos:      file_internal_pb_cluster_proto_msgTypes,
	}.Build()
	File_internal_pb_cluster_proto = out.File
	file_internal_pb_cluster_proto_rawDesc = nil
	file_internal_pb_cluster_proto_goTypes = nil
	file_internal_pb_cluster_proto_depIdxs = nil
}
