// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: internal/pb/cluster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_Unknown      Role = 0
	Role_Follower     Role = 1
	Role_Candidate    Role = 2
	Role_PreCandidate Role = 3
	Role_Leader       Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "Unknown",
		1: "Follower",
		2: "Candidate",
		3: "PreCandidate",
		4: "Leader",
	}
	Role_value = map[string]int32{
		"Unknown":      0,
		"Follower":     1,
		"Candidate":    2,
		"PreCandidate": 3,
		"Leader":       4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_cluster_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_internal_pb_cluster_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_New                   NodeStatus = 0 // 新节点
	NodeStatus_RespondToConfigUpdate NodeStatus = 1 // 响应配置更新
	NodeStatus_DataMigrating         NodeStatus = 2 // 迁移中
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "New",
		1: "RespondToConfigUpdate",
		2: "DataMigrating",
	}
	NodeStatus_value = map[string]int32{
		"New":                   0,
		"RespondToConfigUpdate": 1,
		"DataMigrating":         2,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_cluster_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_pb_cluster_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{1}
}

type PartitionStatus int32

const (
	PartitionStatus_WaitAlloc PartitionStatus = 0 // 等待分配
	PartitionStatus_Allocated PartitionStatus = 1 // 已分配
)

// Enum value maps for PartitionStatus.
var (
	PartitionStatus_name = map[int32]string{
		0: "WaitAlloc",
		1: "Allocated",
	}
	PartitionStatus_value = map[string]int32{
		"WaitAlloc": 0,
		"Allocated": 1,
	}
)

func (x PartitionStatus) Enum() *PartitionStatus {
	p := new(PartitionStatus)
	*p = x
	return p
}

func (x PartitionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartitionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_cluster_proto_enumTypes[2].Descriptor()
}

func (PartitionStatus) Type() protoreflect.EnumType {
	return &file_internal_pb_cluster_proto_enumTypes[2]
}

func (x PartitionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartitionStatus.Descriptor instead.
func (PartitionStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{2}
}

type SlotStatus int32

const (
	SlotStatus_SlotWait      SlotStatus = 0 // slots等待分配
	SlotStatus_SlotMigration SlotStatus = 1 // slots需要迁移
	SlotStatus_SlotReady     SlotStatus = 2 // slots已准备就绪
)

// Enum value maps for SlotStatus.
var (
	SlotStatus_name = map[int32]string{
		0: "SlotWait",
		1: "SlotMigration",
		2: "SlotReady",
	}
	SlotStatus_value = map[string]int32{
		"SlotWait":      0,
		"SlotMigration": 1,
		"SlotReady":     2,
	}
)

func (x SlotStatus) Enum() *SlotStatus {
	p := new(SlotStatus)
	*p = x
	return p
}

func (x SlotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_cluster_proto_enumTypes[3].Descriptor()
}

func (SlotStatus) Type() protoreflect.EnumType {
	return &file_internal_pb_cluster_proto_enumTypes[3]
}

func (x SlotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotStatus.Descriptor instead.
func (SlotStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{3}
}

type NodeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID      uint64     `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`                 // 节点ID
	ServerAddr  string     `protobuf:"bytes,2,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"`          // 节点服务地址
	Role        Role       `protobuf:"varint,3,opt,name=role,proto3,enum=Role" json:"role,omitempty"`           // 节点角色
	PartitionID uint64     `protobuf:"varint,4,opt,name=partitionID,proto3" json:"partitionID,omitempty"`       // 属所分区ID
	Status      NodeStatus `protobuf:"varint,5,opt,name=status,proto3,enum=NodeStatus" json:"status,omitempty"` // 节点状态
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *NodeConfig) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *NodeConfig) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_Unknown
}

func (x *NodeConfig) GetPartitionID() uint64 {
	if x != nil {
		return x.PartitionID
	}
	return 0
}

func (x *NodeConfig) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_New
}

type GatewayConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID  uint64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`  // 节点ID
	TcpAddr string `protobuf:"bytes,2,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"` // 节点tcp对外地址
	WsAddr  string `protobuf:"bytes,3,opt,name=wsAddr,proto3" json:"wsAddr,omitempty"`   // 节点websocket对外地址
	WssAddr string `protobuf:"bytes,4,opt,name=wssAddr,proto3" json:"wssAddr,omitempty"` // 节点 wss对外地址
}

func (x *GatewayConfig) Reset() {
	*x = GatewayConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfig) ProtoMessage() {}

func (x *GatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfig.ProtoReflect.Descriptor instead.
func (*GatewayConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayConfig) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *GatewayConfig) GetTcpAddr() string {
	if x != nil {
		return x.TcpAddr
	}
	return ""
}

func (x *GatewayConfig) GetWsAddr() string {
	if x != nil {
		return x.WsAddr
	}
	return ""
}

func (x *GatewayConfig) GetWssAddr() string {
	if x != nil {
		return x.WssAddr
	}
	return ""
}

type PartitionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionID uint64 `protobuf:"varint,1,opt,name=partitionID,proto3" json:"partitionID,omitempty"` // cluster id
	LeaderID    uint64 `protobuf:"varint,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`       // 领导节点的id
	Version     uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`         // 配置版本
	Replica     uint32 `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`         // 副本数
	Slots       []byte `protobuf:"bytes,5,opt,name=slots,proto3" json:"slots,omitempty"`              // slot bitmap
	// int32 importPartitionID = 7; // 要导入的集群ID
	// bytes importWill = 8; // 将要引入的slots
	Import  *MigrateImport   `protobuf:"bytes,6,opt,name=import,proto3" json:"import,omitempty"`   // 将要引入的slots
	Exports []*MigrateExport `protobuf:"bytes,7,rep,name=exports,proto3" json:"exports,omitempty"` // 将要导出的slots
	// bytes exportWill = 9; // 将要导出的slots
	// bytes exporting = 10; // 正在导出的slot（正在导出的slot将被锁定，不接受数据）
	// ExportedList exportedList = 11; // 已导出的slot
	// bool startExport  = 16; // 是否开始导出
	// repeated int32 importedNodeIDList = 17; // 已导入节点列表
	Nodes  []*NodeConfig   `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`                         // 节点信息
	Status PartitionStatus `protobuf:"varint,9,opt,name=status,proto3,enum=PartitionStatus" json:"status,omitempty"` // 分区状态
}

func (x *PartitionConfig) Reset() {
	*x = PartitionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartitionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionConfig) ProtoMessage() {}

func (x *PartitionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionConfig.ProtoReflect.Descriptor instead.
func (*PartitionConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *PartitionConfig) GetPartitionID() uint64 {
	if x != nil {
		return x.PartitionID
	}
	return 0
}

func (x *PartitionConfig) GetLeaderID() uint64 {
	if x != nil {
		return x.LeaderID
	}
	return 0
}

func (x *PartitionConfig) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PartitionConfig) GetReplica() uint32 {
	if x != nil {
		return x.Replica
	}
	return 0
}

func (x *PartitionConfig) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *PartitionConfig) GetImport() *MigrateImport {
	if x != nil {
		return x.Import
	}
	return nil
}

func (x *PartitionConfig) GetExports() []*MigrateExport {
	if x != nil {
		return x.Exports
	}
	return nil
}

func (x *PartitionConfig) GetNodes() []*NodeConfig {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *PartitionConfig) GetStatus() PartitionStatus {
	if x != nil {
		return x.Status
	}
	return PartitionStatus_WaitAlloc
}

type MigrateImport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImportWill []byte     `protobuf:"bytes,1,opt,name=importWill,proto3" json:"importWill,omitempty"`          // 将要导入的slots
	Importing  []byte     `protobuf:"bytes,2,opt,name=importing,proto3" json:"importing,omitempty"`            // 正在导入的slots
	Imported   []byte     `protobuf:"bytes,3,opt,name=imported,proto3" json:"imported,omitempty"`              // 已导入的slots
	Status     SlotStatus `protobuf:"varint,4,opt,name=status,proto3,enum=SlotStatus" json:"status,omitempty"` // slot状态
}

func (x *MigrateImport) Reset() {
	*x = MigrateImport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateImport) ProtoMessage() {}

func (x *MigrateImport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateImport.ProtoReflect.Descriptor instead.
func (*MigrateImport) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *MigrateImport) GetImportWill() []byte {
	if x != nil {
		return x.ImportWill
	}
	return nil
}

func (x *MigrateImport) GetImporting() []byte {
	if x != nil {
		return x.Importing
	}
	return nil
}

func (x *MigrateImport) GetImported() []byte {
	if x != nil {
		return x.Imported
	}
	return nil
}

func (x *MigrateImport) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SlotWait
}

type MigrateExport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExportPartitionID uint64     `protobuf:"varint,1,opt,name=exportPartitionID,proto3" json:"exportPartitionID,omitempty"` // 要导出的分区ID
	ExportWill        []byte     `protobuf:"bytes,2,opt,name=exportWill,proto3" json:"exportWill,omitempty"`                // 将要导出的slots
	Exporting         []byte     `protobuf:"bytes,3,opt,name=exporting,proto3" json:"exporting,omitempty"`                  // 正在导出的slots
	Exported          []byte     `protobuf:"bytes,4,opt,name=exported,proto3" json:"exported,omitempty"`                    // 已导出的slots
	Status            SlotStatus `protobuf:"varint,5,opt,name=status,proto3,enum=SlotStatus" json:"status,omitempty"`       // slot状态
}

func (x *MigrateExport) Reset() {
	*x = MigrateExport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateExport) ProtoMessage() {}

func (x *MigrateExport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateExport.ProtoReflect.Descriptor instead.
func (*MigrateExport) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *MigrateExport) GetExportPartitionID() uint64 {
	if x != nil {
		return x.ExportPartitionID
	}
	return 0
}

func (x *MigrateExport) GetExportWill() []byte {
	if x != nil {
		return x.ExportWill
	}
	return nil
}

func (x *MigrateExport) GetExporting() []byte {
	if x != nil {
		return x.Exporting
	}
	return nil
}

func (x *MigrateExport) GetExported() []byte {
	if x != nil {
		return x.Exported
	}
	return nil
}

func (x *MigrateExport) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SlotWait
}

type ClusterConfigSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    uint64             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LeaderID   uint64             `protobuf:"varint,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	SlotCount  uint32             `protobuf:"varint,3,opt,name=slotCount,proto3" json:"slotCount,omitempty"` // slot 总数量
	Partitions []*PartitionConfig `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Gateways   []*GatewayConfig   `protobuf:"bytes,5,rep,name=gateways,proto3" json:"gateways,omitempty"`
}

func (x *ClusterConfigSet) Reset() {
	*x = ClusterConfigSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfigSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigSet) ProtoMessage() {}

func (x *ClusterConfigSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigSet.ProtoReflect.Descriptor instead.
func (*ClusterConfigSet) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterConfigSet) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterConfigSet) GetLeaderID() uint64 {
	if x != nil {
		return x.LeaderID
	}
	return 0
}

func (x *ClusterConfigSet) GetSlotCount() uint32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *ClusterConfigSet) GetPartitions() []*PartitionConfig {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *ClusterConfigSet) GetGateways() []*GatewayConfig {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type ExportedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exported []*Exported `protobuf:"bytes,1,rep,name=exported,proto3" json:"exported,omitempty"`
}

func (x *ExportedList) Reset() {
	*x = ExportedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportedList) ProtoMessage() {}

func (x *ExportedList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportedList.ProtoReflect.Descriptor instead.
func (*ExportedList) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ExportedList) GetExported() []*Exported {
	if x != nil {
		return x.Exported
	}
	return nil
}

type Exported struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No    string `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Slots []byte `protobuf:"bytes,2,opt,name=slots,proto3" json:"slots,omitempty"` // 已导出的slots
	Path  string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`   // 对应的备份路径
}

func (x *Exported) Reset() {
	*x = Exported{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exported) ProtoMessage() {}

func (x *Exported) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exported.ProtoReflect.Descriptor instead.
func (*Exported) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *Exported) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *Exported) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *Exported) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID     uint64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`        // 节点ID
	ServerAddr string `protobuf:"bytes,2,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"` // 节点地址
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *JoinReq) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *JoinReq) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

type SyncClustersetConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 配置版本
}

func (x *SyncClustersetConfigReq) Reset() {
	*x = SyncClustersetConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncClustersetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncClustersetConfigReq) ProtoMessage() {}

func (x *SyncClustersetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncClustersetConfigReq.ProtoReflect.Descriptor instead.
func (*SyncClustersetConfigReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *SyncClustersetConfigReq) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID  uint64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`   // 节点ID
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 配置版本
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *Ping) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 骰子结果
type DiceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID uint64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Result int32  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DiceResult) Reset() {
	*x = DiceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiceResult) ProtoMessage() {}

func (x *DiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiceResult.ProtoReflect.Descriptor instead.
func (*DiceResult) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *DiceResult) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *DiceResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type VoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionID   uint64 `protobuf:"varint,1,opt,name=partitionID,proto3" json:"partitionID,omitempty"`     // 分区ID
	NodeID        uint64 `protobuf:"varint,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`               // 节点ID
	ConfigVersion uint64 `protobuf:"varint,3,opt,name=configVersion,proto3" json:"configVersion,omitempty"` // 配置版本
	Round         int32  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`                 // 轮次
}

func (x *VoteReq) Reset() {
	*x = VoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReq) ProtoMessage() {}

func (x *VoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReq.ProtoReflect.Descriptor instead.
func (*VoteReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *VoteReq) GetPartitionID() uint64 {
	if x != nil {
		return x.PartitionID
	}
	return 0
}

func (x *VoteReq) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *VoteReq) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *VoteReq) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type VoteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionID uint64 `protobuf:"varint,1,opt,name=partitionID,proto3" json:"partitionID,omitempty"` // 分区ID
	VoteGranted bool   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"` // 是否同意投票
	Reason      string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`            // 拒绝原因
	Round       int32  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`             // 轮次
}

func (x *VoteResp) Reset() {
	*x = VoteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cluster_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResp) ProtoMessage() {}

func (x *VoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cluster_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResp.ProtoReflect.Descriptor instead.
func (*VoteResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *VoteResp) GetPartitionID() uint64 {
	if x != nil {
		return x.PartitionID
	}
	return 0
}

func (x *VoteResp) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *VoteResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoteResp) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

var File_internal_pb_cluster_proto protoreflect.FileDescriptor

var file_internal_pb_cluster_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x0a,
	0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x19, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x05, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x73, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x73, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x73, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x77, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x77, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x22, 0xb8, 0x02, 0x0a, 0x0f, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x28, 0x0a,
	0x07, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x07,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0d, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x57, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0d, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x11, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x57,
	0x69, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x57, 0x69, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a,
	0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x2a, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x22, 0x35, 0x0a, 0x0c, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x22, 0x44, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x41, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x33, 0x0a, 0x17, 0x73,
	0x79, 0x6e, 0x63, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x38, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x0a, 0x44, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7f, 0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x7c, 0x0a, 0x08, 0x56, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x6f, 0x74, 0x65, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x76, 0x6f,
	0x74, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2a, 0x4e, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x72, 0x65,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x04, 0x2a, 0x43, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x00, 0x12, 0x19,
	0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x2a, 0x2f, 0x0a, 0x0f,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0d, 0x0a, 0x09, 0x57, 0x61, 0x69, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x2a, 0x3c, 0x0a,
	0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x6c, 0x6f, 0x74, 0x57, 0x61, 0x69, 0x74, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x6c, 0x6f,
	0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_cluster_proto_rawDescOnce sync.Once
	file_internal_pb_cluster_proto_rawDescData = file_internal_pb_cluster_proto_rawDesc
)

func file_internal_pb_cluster_proto_rawDescGZIP() []byte {
	file_internal_pb_cluster_proto_rawDescOnce.Do(func() {
		file_internal_pb_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_cluster_proto_rawDescData)
	})
	return file_internal_pb_cluster_proto_rawDescData
}

var file_internal_pb_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_pb_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_pb_cluster_proto_goTypes = []interface{}{
	(Role)(0),                       // 0: Role
	(NodeStatus)(0),                 // 1: NodeStatus
	(PartitionStatus)(0),            // 2: PartitionStatus
	(SlotStatus)(0),                 // 3: SlotStatus
	(*NodeConfig)(nil),              // 4: NodeConfig
	(*GatewayConfig)(nil),           // 5: GatewayConfig
	(*PartitionConfig)(nil),         // 6: PartitionConfig
	(*MigrateImport)(nil),           // 7: MigrateImport
	(*MigrateExport)(nil),           // 8: MigrateExport
	(*ClusterConfigSet)(nil),        // 9: ClusterConfigSet
	(*ExportedList)(nil),            // 10: ExportedList
	(*Exported)(nil),                // 11: Exported
	(*JoinReq)(nil),                 // 12: JoinReq
	(*SyncClustersetConfigReq)(nil), // 13: syncClustersetConfigReq
	(*Ping)(nil),                    // 14: Ping
	(*DiceResult)(nil),              // 15: DiceResult
	(*VoteReq)(nil),                 // 16: VoteReq
	(*VoteResp)(nil),                // 17: VoteResp
}
var file_internal_pb_cluster_proto_depIdxs = []int32{
	0,  // 0: NodeConfig.role:type_name -> Role
	1,  // 1: NodeConfig.status:type_name -> NodeStatus
	7,  // 2: PartitionConfig.import:type_name -> MigrateImport
	8,  // 3: PartitionConfig.exports:type_name -> MigrateExport
	4,  // 4: PartitionConfig.nodes:type_name -> NodeConfig
	2,  // 5: PartitionConfig.status:type_name -> PartitionStatus
	3,  // 6: MigrateImport.status:type_name -> SlotStatus
	3,  // 7: MigrateExport.status:type_name -> SlotStatus
	6,  // 8: ClusterConfigSet.partitions:type_name -> PartitionConfig
	5,  // 9: ClusterConfigSet.gateways:type_name -> GatewayConfig
	11, // 10: ExportedList.exported:type_name -> Exported
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_pb_cluster_proto_init() }
func file_internal_pb_cluster_proto_init() {
	if File_internal_pb_cluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_cluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartitionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateImport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateExport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfigSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exported); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncClustersetConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cluster_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_cluster_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_cluster_proto_goTypes,
		DependencyIndexes: file_internal_pb_cluster_proto_depIdxs,
		EnumInfos:         file_internal_pb_cluster_proto_enumTypes,
		MessageInfos:      file_internal_pb_cluster_proto_msgTypes,
	}.Build()
	File_internal_pb_cluster_proto = out.File
	file_internal_pb_cluster_proto_rawDesc = nil
	file_internal_pb_cluster_proto_goTypes = nil
	file_internal_pb_cluster_proto_depIdxs = nil
}
