import { describe, expect, test } from 'bun:test';
import { getNavigationEntry } from './navigation';

const operationPages = [
  ['users', 'setQuickstartUserToken', 'post', '/user/token'],
  ['routing', 'getQuickstartGatewayRoute', 'get', '/route'],
  ['messages', 'syncQuickstartChannelMessages', 'post', '/channel/messagesync'],
  ['message-send', 'sendChannelMessage', 'post', '/message/send'],
  ['channels', 'upsertChannel', 'post', '/channel'],
  ['channels', 'addChannelSubscribers', 'post', '/channel/subscriber_add'],
  ['channels', 'removeAllChannelSubscribers', 'post', '/channel/subscriber_remove_all'],
  ['channels', 'setTemporaryChannelSubscribers', 'post', '/tmpchannel/subscriber_set'],
  ['channels', 'addChannelDenylistMembers', 'post', '/channel/blacklist_add'],
  ['channels', 'removeChannelDenylistMembers', 'post', '/channel/blacklist_remove'],
  ['channels', 'removeAllChannelDenylistMembers', 'post', '/channel/blacklist_remove_all'],
  ['channels', 'addChannelAllowlistMembers', 'post', '/channel/whitelist_add'],
  ['channels', 'removeChannelAllowlistMembers', 'post', '/channel/whitelist_remove'],
  ['channels', 'removeAllChannelAllowlistMembers', 'post', '/channel/whitelist_remove_all'],
  ['conversations', 'listConversations', 'post', '/conversation/list'],
  ['conversations', 'retryConversations', 'post', '/conversation/retry'],
  ['conversations', 'clearConversationUnread', 'post', '/conversations/clearUnread'],
  ['conversations', 'setConversationUnread', 'post', '/conversations/setUnread'],
  ['conversations', 'hideConversation', 'post', '/conversations/delete'],
  ['conversations', 'activateConversation', 'post', '/conversations/activate'],
] as const;

async function source(relativePath: string) {
  return Bun.file(new URL(relativePath, import.meta.url)).text();
}

describe('Fumadocs OpenAPI reference structure', () => {
  test('uses the documented operation-per-page, tag-grouped generator mode', async () => {
    const generator = await source('../scripts/generate-openapi.ts');

    expect(generator).toContain("per: 'operation'");
    expect(generator).toContain("groupBy: 'tag'");
    expect(generator).toContain('index:');
  });

  test('publishes one bilingual page for every operation under its tag', async () => {
    for (const [tag, operationId, method, path] of operationPages) {
      for (const suffix of ['.mdx', '.en.mdx']) {
        const page = await source(
          `../content/docs/api/product-http/${tag}/${operationId}${suffix}`,
        );

        expect(page).toContain('generated by Fumadocs');
        expect(page).toContain(
          `operations={[{\"path\":\"${path}\",\"method\":\"${method}\"}]}`,
        );
        expect(page.match(/\"path\":/g)).toHaveLength(1);
      }

      expect(
        getNavigationEntry('en', 'api', ['product-http', tag, operationId])?.status,
      ).toBe('published');
    }
  });

  test('keeps tag routes as concise generated indexes', async () => {
    for (const tag of [
      'users',
      'routing',
      'messages',
      'message-send',
      'channels',
      'conversations',
    ]) {
      for (const suffix of ['.mdx', '.en.mdx']) {
        const page = await source(`../content/docs/api/product-http/${tag}/index${suffix}`);

        expect(page).toContain('<Cards>');
        expect(page).not.toContain('operations={[');
      }
    }
  });
});
