#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TIMESTAMP="${WK_BENCH_THREE_NODE_TIMESTAMP:-$(date +%Y%m%d-%H%M%S)}"
BASE_SCRIPT="${WK_BENCH_THREE_NODE_BASE_SCRIPT:-$ROOT_DIR/scripts/bench-wukongimv2-three-nodes-1000ch.sh}"

export WK_BENCH_THREE_NODE_TIMESTAMP="$TIMESTAMP"
export WK_BENCH_CHANNELS="${WK_BENCH_CHANNELS:-10000}"
export WK_BENCH_USERS="${WK_BENCH_USERS:-20000}"
export WK_BENCH_GROUP_MEMBERS="${WK_BENCH_GROUP_MEMBERS:-10}"
export WK_BENCH_CONCURRENCY="${WK_BENCH_CONCURRENCY:-2000}"
export WK_BENCH_DURATION="${WK_BENCH_DURATION:-30s}"
export WK_BENCH_WARMUP="${WK_BENCH_WARMUP:-10s}"
export WK_BENCH_COOLDOWN="${WK_BENCH_COOLDOWN:-5s}"
export WK_BENCH_THREE_NODE_QPS="${WK_BENCH_THREE_NODE_QPS:-100,500,1000}"
export WK_BENCH_THREE_NODE_OUT_DIR="${WK_BENCH_THREE_NODE_OUT_DIR:-$ROOT_DIR/docs/development/perf-runs/${TIMESTAMP}-three-node-10kch}"
export WK_BENCH_PROFILE_SECONDS="${WK_BENCH_PROFILE_SECONDS:-10}"

export WK_PPROF_ENABLE="${WK_PPROF_ENABLE:-true}"
export WK_CLUSTER_MAX_CHANNELS="${WK_CLUSTER_MAX_CHANNELS:-12000}"
export WK_CLUSTER_INITIAL_SLOT_COUNT="${WK_CLUSTER_INITIAL_SLOT_COUNT:-3}"
export WK_CLUSTER_HASH_SLOT_COUNT="${WK_CLUSTER_HASH_SLOT_COUNT:-96}"
export WK_CLUSTER_CHANNEL_REACTOR_COUNT="${WK_CLUSTER_CHANNEL_REACTOR_COUNT:-64}"
export WK_GATEWAY_DEFAULT_SESSION_ASYNC_SEND_DISPATCH_WORKERS="${WK_GATEWAY_DEFAULT_SESSION_ASYNC_SEND_DISPATCH_WORKERS:-256}"

exec "$BASE_SCRIPT" "$@"
