package scripts_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGofailBuildScriptDryRunUsesSafeDefaults(t *testing.T) {
	root := repoRoot(t)
	outPath := filepath.Join(t.TempDir(), "wukongim-gofail")
	workDir := filepath.Join(t.TempDir(), "source")

	cmd := exec.Command("bash", "scripts/build-gofail-binary.sh", "--dry-run", "--out", outPath, "--work-dir", workDir)
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("dry-run failed: %v\n%s", err, output)
	}
	text := string(output)

	for _, want := range []string{
		"gofail_version=go.etcd.io/gofail@v0.2.0",
		"failpoint_packages=pkg/transport",
		"copy_manifest_cmd=git ls-files -z --cached --others --exclude-standard",
		"copy_cmd=tar --null -T - -cf -",
		"enable_cmd=gofail enable pkg/transport",
		"package_name_cmd=GOWORK=off go list -f '{{.Name}}'",
		"postprocess_cmd=scripts/gofail-postprocess-generated.sh",
		"runtime_dep_cmd=GOWORK=off go get go.etcd.io/gofail/runtime@v0.2.0",
		"build_cmd=GOWORK=off go build -o " + outPath + " ./cmd/wukongim",
		"source_dir=" + workDir,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("dry-run output missing %q:\n%s", want, text)
		}
	}
}

func TestGofailPostprocessGeneratedRewritesPackageLine(t *testing.T) {
	root := repoRoot(t)
	workDir := t.TempDir()
	failDir := filepath.Join(workDir, "pkg", "clusterv2", "net")
	if err := os.MkdirAll(failDir, 0o755); err != nil {
		t.Fatal(err)
	}
	failFile := filepath.Join(failDir, "transport.fail.go")
	if err := os.WriteFile(failFile, []byte("// GENERATED BY GOFAIL. DO NOT EDIT.\n\npackage net\n\nvar injected = true\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command("bash", "scripts/gofail-postprocess-generated.sh", workDir, "pkg/clusterv2/net:clusternet")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("postprocess failed: %v\n%s", err, output)
	}

	data, err := os.ReadFile(failFile)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "\npackage clusternet\n") {
		t.Fatalf("package line not rewritten:\n%s", text)
	}
	if !strings.Contains(text, "var injected = true") {
		t.Fatalf("postprocess changed file body:\n%s", text)
	}
}

func TestGofailBuildScriptAllowsExtraFailpointPackages(t *testing.T) {
	root := repoRoot(t)
	outPath := filepath.Join(t.TempDir(), "wukongim-gofail")

	cmd := exec.Command("bash", "scripts/build-gofail-binary.sh", "--dry-run", "--out", outPath, "--package", "pkg/raftlog")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("dry-run failed: %v\n%s", err, output)
	}

	if !strings.Contains(string(output), "failpoint_packages=pkg/transport pkg/raftlog") {
		t.Fatalf("expected package list to include default and extra package:\n%s", output)
	}
}

func TestBuildGofailBinaryDryRunSupportsCommandPackageOverride(t *testing.T) {
	outPath := filepath.Join(t.TempDir(), "wukongimv2-gofail")
	workDir := filepath.Join(t.TempDir(), "src")
	cmd := exec.Command("bash", "scripts/build-gofail-binary.sh",
		"--dry-run",
		"--out", outPath,
		"--work-dir", workDir,
		"--cmd", "./cmd/wukongimv2",
		"--package", "pkg/clusterv2/tasks",
	)
	cmd.Dir = repoRootForScriptTests(t)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("dry run: %v\n%s", err, output)
	}
	text := string(output)
	for _, want := range []string{
		"command_package=./cmd/wukongimv2",
		"failpoint_packages=pkg/transport pkg/clusterv2/tasks",
		"build_cmd=GOWORK=off go build -o " + outPath + " ./cmd/wukongimv2",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("dry run output missing %q:\n%s", want, text)
		}
	}
}

func repoRootForScriptTests(t *testing.T) string {
	return repoRoot(t)
}
