// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: pkg/clusterevent/pb/event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotEventType int32

const (
	SlotEventType_SlotEventTypeNone   SlotEventType = 0
	SlotEventType_SlotEventTypeInit   SlotEventType = 1
	SlotEventType_SlotEventTypeAdd    SlotEventType = 2
	SlotEventType_SlotEventTypeRemove SlotEventType = 3
)

// Enum value maps for SlotEventType.
var (
	SlotEventType_name = map[int32]string{
		0: "SlotEventTypeNone",
		1: "SlotEventTypeInit",
		2: "SlotEventTypeAdd",
		3: "SlotEventTypeRemove",
	}
	SlotEventType_value = map[string]int32{
		"SlotEventTypeNone":   0,
		"SlotEventTypeInit":   1,
		"SlotEventTypeAdd":    2,
		"SlotEventTypeRemove": 3,
	}
)

func (x SlotEventType) Enum() *SlotEventType {
	p := new(SlotEventType)
	*p = x
	return p
}

func (x SlotEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_clusterevent_pb_event_proto_enumTypes[0].Descriptor()
}

func (SlotEventType) Type() protoreflect.EnumType {
	return &file_pkg_clusterevent_pb_event_proto_enumTypes[0]
}

func (x SlotEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotEventType.Descriptor instead.
func (SlotEventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{0}
}

type NodeEventType int32

const (
	NodeEventType_NodeEventTypeNone   NodeEventType = 0
	NodeEventType_NodeEventTypeInit   NodeEventType = 1
	NodeEventType_NodeEventTypeAdd    NodeEventType = 2
	NodeEventType_NodeEventTypeRemove NodeEventType = 3
)

// Enum value maps for NodeEventType.
var (
	NodeEventType_name = map[int32]string{
		0: "NodeEventTypeNone",
		1: "NodeEventTypeInit",
		2: "NodeEventTypeAdd",
		3: "NodeEventTypeRemove",
	}
	NodeEventType_value = map[string]int32{
		"NodeEventTypeNone":   0,
		"NodeEventTypeInit":   1,
		"NodeEventTypeAdd":    2,
		"NodeEventTypeRemove": 3,
	}
)

func (x NodeEventType) Enum() *NodeEventType {
	p := new(NodeEventType)
	*p = x
	return p
}

func (x NodeEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_clusterevent_pb_event_proto_enumTypes[1].Descriptor()
}

func (NodeEventType) Type() protoreflect.EnumType {
	return &file_pkg_clusterevent_pb_event_proto_enumTypes[1]
}

func (x NodeEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEventType.Descriptor instead.
func (NodeEventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{1}
}

type ClusterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotCount    uint32  `protobuf:"varint,1,opt,name=slotCount,proto3" json:"slotCount,omitempty"`       // 槽位数量
	NodeLeader   uint64  `protobuf:"varint,2,opt,name=nodeLeader,proto3" json:"nodeLeader,omitempty"`     // 节点的领导者节点ID
	ReplicaCount uint32  `protobuf:"varint,3,opt,name=replicaCount,proto3" json:"replicaCount,omitempty"` // slot 副本数量
	Nodes        []*Node `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`                // 节点列表
	Slots        []*Slot `protobuf:"bytes,5,rep,name=slots,proto3" json:"slots,omitempty"`                // 槽位列表
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterConfig) GetSlotCount() uint32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *ClusterConfig) GetNodeLeader() uint64 {
	if x != nil {
		return x.NodeLeader
	}
	return 0
}

func (x *ClusterConfig) GetReplicaCount() uint32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

func (x *ClusterConfig) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterConfig) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                // 节点ID
	ServerAddr string `protobuf:"bytes,2,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"` // 节点服务地址
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`              // 槽位ID
	Leader uint64   `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`      // 领导者节点ID
	Nodes  []uint64 `protobuf:"varint,3,rep,packed,name=nodes,proto3" json:"nodes,omitempty"` // 副本节点ID列表
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{2}
}

func (x *Slot) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Slot) GetLeader() uint64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *Slot) GetNodes() []uint64 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType NodeEventType `protobuf:"varint,1,opt,name=eventType,proto3,enum=NodeEventType" json:"eventType,omitempty"` // 事件类型
	Node      []*Node       `protobuf:"bytes,2,rep,name=node,proto3" json:"node,omitempty"`                               // 对应事件的节点
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{3}
}

func (x *NodeEvent) GetEventType() NodeEventType {
	if x != nil {
		return x.EventType
	}
	return NodeEventType_NodeEventTypeNone
}

func (x *NodeEvent) GetNode() []*Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type SlotEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType SlotEventType `protobuf:"varint,1,opt,name=eventType,proto3,enum=SlotEventType" json:"eventType,omitempty"` // 事件类型
	Slot      []*Slot       `protobuf:"bytes,2,rep,name=slot,proto3" json:"slot,omitempty"`                               // 对应事件的槽位
}

func (x *SlotEvent) Reset() {
	*x = SlotEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotEvent) ProtoMessage() {}

func (x *SlotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_clusterevent_pb_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotEvent.ProtoReflect.Descriptor instead.
func (*SlotEvent) Descriptor() ([]byte, []int) {
	return file_pkg_clusterevent_pb_event_proto_rawDescGZIP(), []int{4}
}

func (x *SlotEvent) GetEventType() SlotEventType {
	if x != nil {
		return x.EventType
	}
	return SlotEventType_SlotEventTypeNone
}

func (x *SlotEvent) GetSlot() []*Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

var File_pkg_clusterevent_pb_event_proto protoreflect.FileDescriptor

var file_pkg_clusterevent_pb_event_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22,
	0x36, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x44, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x54, 0x0a,
	0x09, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x22, 0x54, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x2c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x2a, 0x6c, 0x0a, 0x0d, 0x53, 0x6c, 0x6f,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x6c,
	0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x6c, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x6c, 0x6f, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x64, 0x10, 0x02, 0x12, 0x17,
	0x0a, 0x13, 0x53, 0x6c, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x03, 0x2a, 0x6c, 0x0a, 0x0d, 0x4e, 0x6f, 0x64, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x15, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x69, 0x74, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x64, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x4e, 0x6f, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x10, 0x03, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_clusterevent_pb_event_proto_rawDescOnce sync.Once
	file_pkg_clusterevent_pb_event_proto_rawDescData = file_pkg_clusterevent_pb_event_proto_rawDesc
)

func file_pkg_clusterevent_pb_event_proto_rawDescGZIP() []byte {
	file_pkg_clusterevent_pb_event_proto_rawDescOnce.Do(func() {
		file_pkg_clusterevent_pb_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_clusterevent_pb_event_proto_rawDescData)
	})
	return file_pkg_clusterevent_pb_event_proto_rawDescData
}

var file_pkg_clusterevent_pb_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_clusterevent_pb_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_clusterevent_pb_event_proto_goTypes = []interface{}{
	(SlotEventType)(0),    // 0: SlotEventType
	(NodeEventType)(0),    // 1: NodeEventType
	(*ClusterConfig)(nil), // 2: ClusterConfig
	(*Node)(nil),          // 3: Node
	(*Slot)(nil),          // 4: Slot
	(*NodeEvent)(nil),     // 5: NodeEvent
	(*SlotEvent)(nil),     // 6: SlotEvent
}
var file_pkg_clusterevent_pb_event_proto_depIdxs = []int32{
	3, // 0: ClusterConfig.nodes:type_name -> Node
	4, // 1: ClusterConfig.slots:type_name -> Slot
	1, // 2: NodeEvent.eventType:type_name -> NodeEventType
	3, // 3: NodeEvent.node:type_name -> Node
	0, // 4: SlotEvent.eventType:type_name -> SlotEventType
	4, // 5: SlotEvent.slot:type_name -> Slot
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_clusterevent_pb_event_proto_init() }
func file_pkg_clusterevent_pb_event_proto_init() {
	if File_pkg_clusterevent_pb_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_clusterevent_pb_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_clusterevent_pb_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_clusterevent_pb_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_clusterevent_pb_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_clusterevent_pb_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_clusterevent_pb_event_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_clusterevent_pb_event_proto_goTypes,
		DependencyIndexes: file_pkg_clusterevent_pb_event_proto_depIdxs,
		EnumInfos:         file_pkg_clusterevent_pb_event_proto_enumTypes,
		MessageInfos:      file_pkg_clusterevent_pb_event_proto_msgTypes,
	}.Build()
	File_pkg_clusterevent_pb_event_proto = out.File
	file_pkg_clusterevent_pb_event_proto_rawDesc = nil
	file_pkg_clusterevent_pb_event_proto_goTypes = nil
	file_pkg_clusterevent_pb_event_proto_depIdxs = nil
}
