WK_NODE_ID=3
WK_NODE_NAME=wk-node3
WK_NODE_DATA_DIR=/var/lib/wukongim
WK_CLUSTER_LISTEN_ADDR=0.0.0.0:7000
WK_CLUSTER_HASH_SLOT_COUNT=256
WK_CLUSTER_INITIAL_SLOT_COUNT=10
WK_CLUSTER_LONG_POLL_MAX_WAIT=2s
WK_CLUSTER_DATA_PLANE_RPC_TIMEOUT=1s
WK_CLUSTER_CONTROLLER_REPLICA_N=3
WK_CLUSTER_SLOT_REPLICA_N=3
WK_CLUSTER_NODES=[{"id":1,"addr":"wk-node1:7000"},{"id":2,"addr":"wk-node2:7000"},{"id":3,"addr":"wk-node3:7000"}]
WK_API_LISTEN_ADDR=0.0.0.0:5001
WK_GATEWAY_LISTENERS=[{"name":"tcp-wkproto","network":"tcp","address":"0.0.0.0:5100","transport":"gnet","protocol":"wkproto"},{"name":"ws-gateway","network":"websocket","address":"0.0.0.0:5200","transport":"gnet","protocol":"wsmux"}]
WK_LOG_DIR=/var/lib/wukongim/logs
WK_HEALTH_DEBUG_ENABLE=true
WK_EXTERNAL_TCPADDR=127.0.0.1:15102
WK_EXTERNAL_WSADDR=ws://127.0.0.1:15202
