const statusLabelIds: Record<string, string> = {
  active: "status.active",
  alive: "status.alive",
  append_catchup: "status.appendCatchup",
  compacted: "status.compacted",
  compaction_degraded: "status.compactionDegraded",
  completed: "status.completed",
  complete: "status.complete",
  closing: "status.closing",
  created: "status.created",
  dead: "status.dead",
  deleting: "status.deleting",
  done: "status.done",
  draining: "status.draining",
  failed: "status.failed",
  follower: "status.follower",
  fresh: "status.fresh",
  healthy: "status.healthy",
  in_sync: "status.inSync",
  isr_insufficient: "status.isrInsufficient",
  leader: "status.leader",
  leader_missing: "status.leaderMissing",
  missing: "status.missing",
  learner: "status.learner",
  joining: "status.joining",
  leaving: "status.leaving",
  needs_snapshot: "status.needsSnapshot",
  no_leader: "status.noLeader",
  not_ready: "status.notReady",
  offline: "status.offline",
  online: "status.online",
  pending: "status.pending",
  participant_progress: "status.participantProgress",
  quorum_lost: "status.quorumLost",
  ready: "status.ready",
  retrying: "status.retrying",
  running: "status.running",
  removed: "status.removed",
  service_unavailable: "status.serviceUnavailable",
  skipped: "status.skipped",
  snapshot_required: "status.snapshotRequired",
  snapshot_transferring: "status.snapshotTransferring",
  snapshot: "status.snapshot",
  stale: "status.stale",
  staged: "status.staged",
  succeeded: "status.succeeded",
  suspect: "status.suspect",
  unknown: "status.unknown",
  verified: "status.verified",
  exporting: "status.exporting",
  rolling_back: "status.rollingBack",
}

export function getStatusLabelMessageId(value: string) {
  return statusLabelIds[value.toLowerCase()]
}
